{
    "title" : "An Error Occurred While Decrypting The SitecorePassword Configuration Element Value",
    "uri" : "http://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
    "printableUri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
    "clickUri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
    "excerpt" : "I'm setting up Coveo for Sitecore on a CM instance in a remote setup (Sitecore and CES on separate servers). ... Installing the package (v1188) was successful and I was able to enter the configurat...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1120,
    "percentScore" : 75.30528,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "An Error Occurred While Decrypting The SitecorePassword Configuration Element Value",
      "sysauthor" : "jvohs5",
      "sysurihash" : "4ðPxEJ29gn6CyJPc",
      "urihash" : "4ðPxEJ29gn6CyJPc",
      "numberofanswers" : 2,
      "sysuri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160355,
      "questionaskeddatestring" : "·\n            Dec 08, 2015 at 04:15 PM ·",
      "tags" : [ "entryption", "queuepassword", "sitecorepassword" ],
      "sysconcepts" : "control panel ; Sitecore Password ; Coveo ; configuration ; remote setup ; package ; RijndaelEncryptionKeys file ; using Solr ; validations ; queuepassword ; SkipSiteNameValidation ; permissions ; sitecorepassword ; SearchProvider ; searching intially",
      "concepts" : "control panel ; Sitecore Password ; Coveo ; configuration ; remote setup ; package ; RijndaelEncryptionKeys file ; using Solr ; validations ; queuepassword ; SkipSiteNameValidation ; permissions ; sitecorepassword ; SearchProvider ; searching intially",
      "printableuri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942415000,
      "permanentid" : "b8a62b1ee8ae355ae6cdc603ac7d4e73a9bfd83848ad66ce6bffe379c516",
      "syslanguage" : [ "English" ],
      "transactionid" : 160355,
      "title" : "An Error Occurred While Decrypting The SitecorePassword Configuration Element Value",
      "date" : 1449619200000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Sébastien Belzile", "Jean-François L'Heureux" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "jvohs5", "jvohs5", "Jean-François L'Heureux \u2666\u2666", "Jean-François L'Heureux \u2666\u2666", "jvohs5", "Jean-François L'Heureux \u2666\u2666" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5447967,
      "numberofcomments" : 6,
      "size" : 103758,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911578267,
      "acceptedanswers" : 1,
      "syssize" : 103758,
      "sysdate" : 1449619200000,
      "author" : "jvohs5",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>I'm setting up Coveo for Sitecore on a CM instance in a remote setup (Sitecore and CES on separate servers). Installing the package (v1188) was successful and I was able to enter the configuration info at the end of the install. I then proceeded through <a rel=\"nofollow\" href=\"https://developers.coveo.com/display/public/SC201501/Setting+Up+Coveo+for+Sitecore+in+a+Remote+Server+Configuration\">this</a> document to set up the instance for remote CES. I also logged into the Sitecore control panel and changed the Sitecore Password that Coveo uses.</p> \n<p>After I was set up and verified all values looked correct in Coveo.SearchProvider.config, including encrypted keys for QueuePassword and SitecorePassword I enabled the Coveo.SearchProvder.config file, cycled IIS, and refreshed. I received the \"Request is not available in this context\" error message. The Coveo.Search.log file contains the output below. </p> \n<p>I've tried updating both passwords through the control panel which updates the config file, but still shows the error below. I've also noticed the RijndaelEncryptionKeys file does not have it's modified timestamp updated after entering new passwords. Maybe I'm wrong in expecting it to update. I've tried deleting this file and updating the passwords, which works to an extent. The QueuePassword related errors in the log will go away when I do that.</p> \n<p>I've also tried removing the configs entirely and reinstalling the CfS package. I should also add that this works correctly on my local machine (CES and Sitecore on same machine). Anything else I can try?</p> \n<pre><code> 34792 13:27:16 Coveo.Framework.Configuration.CoveoIndexConfiguration.set_QueuePassword(:0) WARN  An error occurred while decrypting the QueuePassword configuration element value. The element value will be used as is assuming it is unencrypted. You can encrypt this password by using the Indexing Queue Connection Configuration wizard located at Control Panel > Coveo Search > Configuration.\n Exception: System.Security.Cryptography.CryptographicException\n Message: Length of the data to decrypt is invalid.\n Source: mscorlib\n    at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n    at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n    at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n    at System.IO.Stream.Close()\n    at Coveo.Connectors.Utilities.Encryption.RijndaelEncrypter.DecryptData(Byte[] p_DataToDecrypt)\n    at Coveo.Framework.Security.ConfigurationValueEncrypter.Decrypt(String p_EncryptedValue)\n    at Coveo.Framework.Configuration.CoveoIndexConfiguration.set_QueuePassword(String value)\n \n 34792 13:27:16 Coveo.Framework.Configuration.CoveoIndexConfiguration.set_SitecorePassword(:0) WARN  An error occurred while decrypting the SitecorePassword configuration element value. The element value will be used as is assuming it is unencrypted. You can encrypt this password by using the Sitecore Credentials Configuration wizard located at Control Panel > Coveo Search > Configuration.\n Exception: System.Security.Cryptography.CryptographicException\n Message: Length of the data to decrypt is invalid.\n Source: mscorlib\n    at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n    at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n    at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n    at System.IO.Stream.Close()\n    at Coveo.Connectors.Utilities.Encryption.RijndaelEncrypter.DecryptData(Byte[] p_DataToDecrypt)\n    at Coveo.Framework.Security.ConfigurationValueEncrypter.Decrypt(String p_EncryptedValue)\n    at Coveo.Framework.Configuration.CoveoIndexConfiguration.set_SitecorePassword(String value)\n \n 34792 13:27:16 Coveo.Framework.Configuration.CoveoIndexConfiguration.set_QueuePassword(:0) WARN  An error occurred while decrypting the QueuePassword configuration element value. The element value will be used as is assuming it is unencrypted. You can encrypt this password by using the Indexing Queue Connection Configuration wizard located at Control Panel > Coveo Search > Configuration.\n Exception: System.Security.Cryptography.CryptographicException\n Message: Length of the data to decrypt is invalid.\n Source: mscorlib\n    at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n    at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n    at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n    at System.IO.Stream.Close()\n    at Coveo.Connectors.Utilities.Encryption.RijndaelEncrypter.DecryptData(Byte[] p_DataToDecrypt)\n    at Coveo.Framework.Security.ConfigurationValueEncrypter.Decrypt(String p_EncryptedValue)\n    at Coveo.Framework.Configuration.CoveoIndexConfiguration.set_QueuePassword(String value)\n \n 34792 13:27:16 Coveo.Framework.Configuration.CoveoIndexConfiguration.set_SitecorePassword(:0) WARN  An error occurred while decrypting the SitecorePassword configuration element value. The element value will be used as is assuming it is unencrypted. You can encrypt this password by using the Sitecore Credentials Configuration wizard located at Control Panel > Coveo Search > Configuration.\n Exception: System.Security.Cryptography.CryptographicException\n Message: Length of the data to decrypt is invalid.\n Source: mscorlib\n    at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n    at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n    at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n    at System.IO.Stream.Close()\n    at Coveo.Connectors.Utilities.Encryption.RijndaelEncrypter.DecryptData(Byte[] p_DataToDecrypt)\n    at Coveo.Framework.Security.ConfigurationValueEncrypter.Decrypt(String p_EncryptedValue)\n    at Coveo.Framework.Configuration.CoveoIndexConfiguration.set_SitecorePassword(String value)\n \n 34792 13:27:17 Coveo.Framework.Configuration.CoveoIndexConfiguration.ValidateSitecoreCredentials(:0) WARN  Unable to validate the Sitecore credentials. You can disable this validation using the \"SkipSitecoreLoginCheck\" configuration element. But, be aware that wrong Sitecore credentials will prevent the permissions from being applied correctly on indexed documents.\n Exception: System.Web.HttpException\n Message: Request is not available in this context\n Source: System.Web\n    at System.Web.Profile.SqlProfileProvider.GetPropertyValuesFromDatabase(String userName, SettingsPropertyValueCollection svc)\n    at System.Web.Profile.SqlProfileProvider.GetPropertyValues(SettingsContext sc, SettingsPropertyCollection properties)\n    at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)\n    at System.Configuration.SettingsBase.SetPropertyValueByName(String propertyName, Object propertyValue)\n    at System.Configuration.SettingsBase.set_Item(String propertyName, Object value)\n    at System.Web.Profile.ProfileBase.SetInternal(String propertyName, Object value)\n    at System.Web.Profile.ProfileBase.set_Item(String propertyName, Object value)\n    at Sitecore.Data.DataProviders.NullRetryer.ExecuteNoResult(Action action, Action recover)\n    at Sitecore.Security.UserProfile.SetPropertyValueCore(String propertyName, Object value)\n    at Sitecore.Security.UserProfile.get_CustomProperties()\n    at Sitecore.Security.UserProfile.GetCustomProperty(String propertyName)\n    at Sitecore.Security.SecurityUtil.GetUserDigestCredentials(User user, Boolean withoutDomain)\n    at Sitecore.Security.SecurityUtil.UpdateDigestCredentials(String username, String password)\n    at Sitecore.Security.SitecoreMembershipProvider.ValidateUser(String username, String password)\n    at Sitecore.Security.Authentication.AuthenticationHelper.ValidateUser(String userName, String password)\n    at Sitecore.Security.Authentication.MembershipAuthenticationProvider.Login(String userName, String password, Boolean persistent)\n    at Coveo.Framework.Configuration.CoveoIndexConfiguration.ValidateSitecoreCredentials()\n \n 34792 13:27:18 Coveo.Framework.Configuration.CoveoIndexConfiguration.ValidateSiteName(:0) WARN  Unable to validate the Sitecore website. You can disable this validation using the \"SkipSiteNameValidation\" configuration element. But, be aware that using an invalid site name will prevent the Coveo security provider from resolving permissions.\n Exception: System.Web.HttpException\n Message: Response is not available in this context.\n Source: System.Web\n    at System.Web.HttpContext.get_Response()\n    at Sitecore.Security.Authentication.AuthenticationHelper.HandleAuthenticationError()\n    at Sitecore.Security.Authentication.FormsAuthenticationHelper.GetCurrentUser()\n    at Sitecore.Security.Authentication.AuthenticationHelper.GetActiveUser()\n    at Sitecore.Security.AccessControl.ItemAccess.IsAllowed(Item item, AccessRight accessRight)\n    at Sitecore.Data.Managers.ItemProvider.ApplySecurity(Item item, SecurityCheck securityCheck)\n    at Sitecore.ContentTesting.Pipelines.ItemProvider.GetItem.GetItemUnderTestProcessor.Process(GetItemArgs args)\n    at (Object , Object[] )\n    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)\n    at Sitecore.Data.Managers.PipelineBasedItemProvider.ExecuteAndReturnResult[TArgs,TResult](String pipelineName, String pipelineDomain, Func`1 pipelineArgsCreator, Func`1 fallbackResult)\n    at Sitecore.Data.Managers.ItemManager.GetItem(String itemPath, Language language, Version version, Database database)\n    at Sitecore.FXM.Matchers.DomainMatcherRepository.GetAllDomainMatchers(IDatabase database)\n    at Sitecore.FXM.Sites.FxmSiteProvider.GetFxmSites()\n    at Sitecore.FXM.Sites.FxmSiteProvider.get_FxmSites()\n    at Sitecore.FXM.Sites.FxmSiteProvider.GetSites()\n    at Sitecore.Sites.SitecoreSiteProvider.<GetSites>b__6(SiteProvider p)\n    at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()\n    at Sitecore.Sites.SiteCollection.AddRange(IEnumerable`1 sites)\n    at Sitecore.Sites.SitecoreSiteProvider.GetSites()\n    at Sitecore.Sites.SiteContextFactory.GetSites()\n    at Sitecore.Sites.SiteContextFactory.GetSiteInfo(String name)\n    at Sitecore.Sites.SiteContextFactory.GetSiteContext(String name)\n    at Coveo.Framework.Sites.SiteContextFactoryWrapper.GetSiteContext(String p_SiteName)\n    at Coveo.Framework.Configuration.CoveoIndexConfiguration.ValidateSiteName()\n \n 34792 13:27:18 Coveo.SearchProvider.ProviderIndexBase.Initialize(:0) ERROR An error while Initializing occurred\n Exception: System.Web.HttpException\n Message: Request is not available in this context\n Source: System.Web\n    at System.Web.HttpContext.get_Request()\n    at Sitecore.Web.WebUtil.GetServerUrl(Boolean forcePort)\n    at Coveo.Framework.Utils.UrlUtilities.GetServerUrl()\n    at Coveo.SearchProvider.Documents.ItemLinkFactory..ctor(CoveoIndexConfiguration p_Configuration, IUrlUtilities p_UrlUtilities, ISiteContextFactory p_SiteContextFactory, IPipelineRunnerHandler p_PipelineRunnerHandler)\n    at Coveo.SearchProvider.IndexOperations.Initialize(CoveoIndexConfiguration p_Configuration, IBinaryDataPropertiesWriter p_BinaryDataPropertiesWriter)\n    at Coveo.SearchProvider.ProviderIndexBase.Initialize(IIndexDocumentPropertyMapper`1 p_DocumentTypeMapper)\n</code></pre>\n                </div>",
      "sitemaplastmodified" : 1449619200000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942415000,
      "questionnumber" : 6900,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "jvohs5",
      "sitename" : "Answers",
      "sysrowid" : 5447967,
      "uri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "An Error Occurred While Decrypting The SitecorePassword Configuration Element Value",
    "Uri" : "http://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
    "PrintableUri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
    "ClickUri" : "https://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/6900/an-error-occurred-while-decrypting-the-sitecorepas.html",
    "Excerpt" : "I'm setting up Coveo for Sitecore on a CM instance in a remote setup (Sitecore and CES on separate servers). ... Installing the package (v1188) was successful and I was able to enter the configurat...",
    "FirstSentences" : null
  }