{
    "title" : "Coveo for sitecore not working on a new instance",
    "uri" : "http://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
    "printableUri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
    "clickUri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
    "excerpt" : "I took the training a few days ago and I have a fresh instance of jestream working fine. ... I tried to install coveo for sitecore on a new instance but some of the services are not working on the ...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1030,
    "percentScore" : 72.21627,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Coveo for sitecore not working on a new instance",
      "sysauthor" : "Diego",
      "sysurihash" : "cYv7nZu44A6EP5ðF",
      "urihash" : "cYv7nZu44A6EP5ðF",
      "numberofanswers" : 5,
      "sysuri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160350,
      "questionaskeddatestring" : "·\n            Dec 09, 2014 at 02:43 PM ·",
      "tags" : [ "coveoforsitecore", "installerror" ],
      "sysconcepts" : "coveo ; sitecore ; localhost ; diagnostics ; secret ; configuration ; indexes ; using lowercase ; json response ; jestream working ; copy-paste ; searchprovider ; extension",
      "concepts" : "coveo ; sitecore ; localhost ; diagnostics ; secret ; configuration ; indexes ; using lowercase ; json response ; jestream working ; copy-paste ; searchprovider ; extension",
      "printableuri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942039000,
      "permanentid" : "2db2b5f8134ab9305e4c904a89a2b7980bae369883a7bf1c8e6e3e7b904e",
      "syslanguage" : [ "English" ],
      "transactionid" : 160350,
      "title" : "Coveo for sitecore not working on a new instance",
      "date" : 1427241600000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Diego", "Luc Bergeron", "Jean-François L'Heureux", "taebalikhan", "dlanglois" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "Diego", "Luc Bergeron \u2666", "Diego" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5447477,
      "numberofcomments" : 3,
      "size" : 108976,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911577776,
      "acceptedanswers" : 1,
      "syssize" : 108976,
      "sysdate" : 1427241600000,
      "author" : "Diego",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>hi guys</p>\n<p>I took the training a few days ago and I have a fresh instance of jestream working fine.\nI tried to install coveo for sitecore on a new instance but some of the services are not working on the diagnostics page\nI can open <a href=\"http://localhost:8080/rest/search\">http://localhost:8080/rest/search</a> and see the jetsream json response. \nI can open <a href=\"http://localhost:8081/\">http://localhost:8081/</a> and see the indexes of jetstream there but not mine(because I never got a chance to index)\nAll coveo services are running on my system but this is what I get on the diagnostics page</p>\n<p>Sitecore's Configuration    Up and running\nCoveo Pipeline Names Configuration    Up and running\nAdmin Service    Up and running\nCoveo Entreprise Search    Up and running\nCoveo Search REST Endpoint ()    The remote server returned an error: (500) Internal Server Error.\nCoveo Search Web Service    Could not establish trust relationship for the SSL/TLS secure channel with authority 'localhost:52810'.\nCoveo Security Service    Up and running\nCoveo Security Provider    No security provider was found with name 'Sitecore Security Provider for mymachine-myhost' on instance default\nRabbitMQ    None of the specified endpoints were reachable</p>\n<p>Here are some of the erros I see on the logs:\n13384 14:58:54 ERROR StateVerifier has encountered an error while verifying the component \"Coveo Search REST Endpoint ()\".\nException: System.Net.WebException\nMessage: The remote server returned an error: (500) Internal Server Error.\nSource: System\n   at System.Net.HttpWebRequest.GetResponse()\n   at Coveo.SearchProvider.Applications.StateVerifier.c_<em>DisplayClassd.b</em>_c()\n   at Coveo.SearchProvider.Applications.BaseVerifier.VerifyComponent(Func`1 p_VerifyMethod, String p_ComponentName)</p>\n<p>Message: Could not find property 'restEndpointConfiguration' on object of type: Sitecore.ContentSearch.ContentSearchConfiguration\nSource: Sitecore.Kernel\n   at Sitecore.Diagnostics.Assert.IsTrue(Boolean condition, String message)\n   at Sitecore.Configuration.Factory.AssignProperties(Object obj, Object[] properties)\n   at Sitecore.Configuration.Factory.AssignProperties(XmlNode configNode, String[] parameters, Object obj, Boolean assert, Boolean deferred, IFactoryHelper helper)\n   at Sitecore.Configuration.Factory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper)\n   at Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert)</p>\n<p>I'm sure I am missing a configuration but I donÂ´t know which ones.\nany ideas?</p>\n<p>Message: Could not establish trust relationship for the SSL/TLS secure channel with authority 'localhost:52810'.\nSource: mscorlib</p>\n<p>Server stack trace: \n   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)\n   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)\n   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)\n   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)\n   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)\n   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)</p>\n<p>Exception: System.Net.WebException\nMessage: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.\nSource: System\n   at System.Net.HttpWebRequest.GetResponse()\n   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)</p>\n<p>Nested Exception</p>\n<p>Exception: System.Security.Authentication.AuthenticationException\nMessage: The remote certificate is invalid according to the validation procedure.\nSource: System\n   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)\n   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)\n   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)\n   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)\n   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)\n   at System.Net.ConnectStream.WriteHeaders(Boolean async)</p>\n<p>13384 14:58:54 ERROR StateVerifier has encountered an error while verifying the component \"Coveo Security Provider\".\nException: System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]</p>\n<p>EDITING TO ADD THE REST.config file</p>\n<p>http://www.sitecore.net/xmlconfig/\">\n  \n    \n      \n      \n        \n      \n      \n      \n      \n      \n        \n        \n      \n    \n    \n      \n        \n        \n          \n          replace this by your own application secret\n          \n          00:00:30\n          \n          /coveo/rest\n          \n          01:00:00\n          \n          <a href=\"http://localhost:8080\">http://localhost:8080</a>\n        \n      \n    \n  \n</p>\n\n                </div>",
      "sitemaplastmodified" : 1427241600000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942039000,
      "questionnumber" : 3212,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "Diego",
      "sitename" : "Answers",
      "sysrowid" : 5447477,
      "uri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Coveo for sitecore not working on a new instance",
    "Uri" : "http://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
    "PrintableUri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
    "ClickUri" : "https://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/3212/coveo-for-sitecore-not-working-on-a-new-instance.html",
    "Excerpt" : "I took the training a few days ago and I have a fresh instance of jestream working fine. ... I tried to install coveo for sitecore on a new instance but some of the services are not working on the ...",
    "FirstSentences" : null
  }