{
    "title" : "Coveo 4.0 remote server error",
    "uri" : "http://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
    "printableUri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
    "clickUri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
    "excerpt" : "The Coveo CES 7.0 (8691) is running on the same server, and I also have the Coveo Search API 8.0.1130 installed. ... When I try to index the coveo master and web indexes in Sitecore, I'm getting th...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1165,
    "percentScore" : 76.803215,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Coveo 4.0 remote server error",
      "sysauthor" : "seinarsson",
      "sysurihash" : "V281RCky2o0KZM0v",
      "urihash" : "V281RCky2o0KZM0v",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160363,
      "questionaskeddatestring" : "·\n            Jan 20, 2017 at 01:41 PM ·",
      "tags" : [ "coveoforsitecore", "4.0" ],
      "sysconcepts" : "coveo ; Sitecore ; server ; IP ; private network ; connected host ; exception detected ; w3wp crashing ; Search API ; infrastructure",
      "concepts" : "coveo ; Sitecore ; server ; IP ; private network ; connected host ; exception detected ; w3wp crashing ; Search API ; infrastructure",
      "printableuri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942957000,
      "permanentid" : "993b825918f0ee86c6b5adace2729cfd4bbbb027725c378b7c2d90a5bd74",
      "syslanguage" : [ "English" ],
      "transactionid" : 160363,
      "title" : "Coveo 4.0 remote server error",
      "date" : 1484870400000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Luc Bergeron" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "seinarsson", "seinarsson", "Luc Bergeron \u2666" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5448698,
      "numberofcomments" : 3,
      "size" : 77636,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911578978,
      "acceptedanswers" : 0,
      "syssize" : 77636,
      "sysdate" : 1484870400000,
      "author" : "seinarsson",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>I have a 8.0 rev. 150812 Sitecore CM site, running Coveo for Sitecore 80 4.0 (780). The Coveo CES 7.0 (8691) is running on the same server, and I also have the Coveo Search API 8.0.1130 installed.</p> \n<p>When I try to index the coveo master and web indexes in Sitecore, I'm getting the error shown below as well as w3wp crashing...</p> \n<p>The IP being referenced in the error (10.205.226.65:3128), I haven't been able to find it being referenced in any configs or settings, and the port (3128) isn't listed as a required port for Coveo.</p> \n<p>Any ideas what could be causing this error, or where I can find more info about it?</p> \n<pre><code> 10556 11:07:21 ERROR Unhandled exception detected. The ASP.NET worker process will be terminated. \n Exception: System.Net.WebException\n Message: Unable to connect to the remote server\n Source: System\n    at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)\n    at System.Net.HttpWebRequest.GetRequestStream()\n    at Coveo.Framework.Utils.Rest.HttpClient.CreateRequest(String p_Method, String p_Url, String p_Body, Boolean p_PreserveMethodOnRedirect)\n    at Coveo.Framework.Utils.Rest.HttpClient.PostAsync(String p_Url, String p_Body, RequestCallbackDelegate p_RequestCallback)\n    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\n    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\n    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n    at System.Threading.ThreadHelper.ThreadStart(Object obj)\n \n Nested Exception\n \n Exception: System.Net.Sockets.SocketException\n Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.205.226.65:3128\n Source: System\n    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)\n    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\n</code></pre>\n                </div>",
      "sitemaplastmodified" : 1484870400000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942957000,
      "questionnumber" : 10228,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "seinarsson",
      "sitename" : "Answers",
      "sysrowid" : 5448698,
      "uri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Coveo 4.0 remote server error",
    "Uri" : "http://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
    "PrintableUri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
    "ClickUri" : "https://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/10228/coveo-40-remote-server-error.html",
    "Excerpt" : "The Coveo CES 7.0 (8691) is running on the same server, and I also have the Coveo Search API 8.0.1130 installed. ... When I try to index the coveo master and web indexes in Sitecore, I'm getting th...",
    "FirstSentences" : null
  }