{
    "title" : "Index rebuild from sitecore crash",
    "uri" : "http://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
    "printableUri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
    "clickUri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
    "excerpt" : "I absolutely don't know why but seems that in the following call: ... Looks like you have 2 fields that ends up with the same CoveoFieldName (encoded for the index). ... Please check your external ...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1157,
    "percentScore" : 76.53906,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Index rebuild from sitecore crash",
      "sysauthor" : "danteciambella",
      "sysurihash" : "TEjeBSJ7qIkzOYb9",
      "urihash" : "TEjeBSJ7qIkzOYb9",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160361,
      "questionaskeddatestring" : "·\n            Nov 10, 2016 at 11:48 AM ·",
      "tags" : [ "index", "rebuild" ],
      "sysconcepts" : "fsiz122xe12345 ; indexes ; CoveoFieldName ; fieldMap config ; trap ; customization ; done ; Installation ; externalFields ; fieldNames ; defaultIndexConfiguration",
      "concepts" : "fsiz122xe12345 ; indexes ; CoveoFieldName ; fieldMap config ; trap ; customization ; done ; Installation ; externalFields ; fieldNames ; defaultIndexConfiguration",
      "printableuri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517942834000,
      "permanentid" : "4bc688ab75517702361a6dc9155a9ba08f1120d3b5aa1057f085cea90742",
      "syslanguage" : [ "English" ],
      "transactionid" : 160361,
      "title" : "Index rebuild from sitecore crash",
      "date" : 1479081600000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "danteciambella" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "Dominic Berube \u2666\u2666", "danteciambella", "Dominic Berube \u2666\u2666", "danteciambella", "Jean-François L'Heureux \u2666\u2666" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5448531,
      "numberofcomments" : 5,
      "size" : 87864,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911578829,
      "acceptedanswers" : 1,
      "syssize" : 87864,
      "sysdate" : 1479081600000,
      "author" : "danteciambella",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>Good morning Guys,</p> \n<p>I installed the following Coveo component with Sitecore 8.2 initial release:</p> \n<ul> \n <li><p> Coveo Enterprise Search 7.0 x64 (8541) for Sitecore.exe </p> </li> \n <li><p> Coveo Search API 8.0.1130.exe </p> </li> \n <li><p> Coveo for Sitecore 82 4.0 (450)</p> </li> \n</ul> \n<p>when I try to rebuild the index using Control Panel Index Manager I have the following trap:</p> \n<pre><code> Job started: Index_Update_IndexName=Coveo_master_index|#Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains more than one matching element\n    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\n    at Coveo.AbstractLayer.FieldManagement.AdminModuleFieldsHandler.GetCesFieldsToDeleteAndAdd(IEnumerable`1 p_CesFields, IEnumerable`1 p_SitecoreFields, List`1& p_CesFieldsToDelete, IList`1& p_CesFieldsToAdd)\n    at Coveo.AbstractLayer.FieldManagement.AdminModuleFieldsHandler.UpdateFieldSetAndFields(String p_FieldSetName, String p_IndexName, ForeignKeysConfiguration p_ForeignKeysConfiguration)\n    at Coveo.AbstractLayer.Communication.CES.AdminModule.SetUpRequirements(String p_ServerUrl, String p_TargetSite, Boolean p_ExpandUsers, ForeignKeysConfiguration p_ForeignKeysConfiguration, IList`1 p_RankingIgnoredFields)\n    at Coveo.AbstractLayer.Communication.CES.CESCommunication.InitializeAdminModule()\n    at Coveo.AbstractLayer.Communication.CES.CESCommunication.Initialize()\n    at Coveo.SearchProvider.AbstractProviderUpdateContext..ctor(ISearchIndexSummary p_IndexSummary, IIndexCommunication p_Communication)\n    at Coveo.SearchProvider.ProviderUpdateContext..ctor(ISearchIndex p_Index, IIndexCommunication p_Communication)\n    at Coveo.SearchProvider.ProviderIndex.CreateUpdateContext()\n    at Coveo.SearchProvider.ProviderIndex.<Rebuild>b__3e()\n    at Coveo.SearchProvider.ProviderIndex.TryPerformIndexingOperation(IndexingOptions p_IndexingOptions, Action p_Action)\n    at Coveo.SearchProvider.ProviderIndex.Rebuild()\n    --- End of inner exception stack trace ---\n    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\n    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\n    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n    at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)\n    at Sitecore.Jobs.JobRunner.RunMethod(JobArgs args)\n    at (Object , Object[] )\n    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)\n    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)\n    at Sitecore.Jobs.Job.ThreadEntry(Object state)\n\n</code></pre> \n<p>I absolutely don't know why but seems that in the following call:</p> \n<pre><code> GetCesFieldsToDeleteAndAdd(System.Collections.Generic.IEnumerable<Coveo.AdminService.AdminService.FieldConfig> p_CesFields, System.Collections.Generic.IEnumerable<Coveo.Framework.Fields.Config.FieldConfig> p_SitecoreFields, out System.Collections.Generic.List<Coveo.AdminService.AdminService.FieldConfig> p_CesFieldsToDelete, out System.Collections.Generic.IList<Coveo.Framework.Fields.Config.FieldConfig> p_CesFieldsToAdd)\n\n</code></pre> \n<p>the <code>source.SingleOrDefault((Coveo.Framework.Fields.Config.FieldConfig f) => f.CoveoFieldName == cesField.FieldName)</code> return more than one element.</p> \n<p>Please any suggestion?</p>\n                </div>",
      "sitemaplastmodified" : 1479081600000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517942834000,
      "questionnumber" : 9536,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "danteciambella",
      "sitename" : "Answers",
      "sysrowid" : 5448531,
      "uri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Index rebuild from sitecore crash",
    "Uri" : "http://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
    "PrintableUri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
    "ClickUri" : "https://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/9536/index-rebuild-from-sitecore-crash.html",
    "Excerpt" : "I absolutely don't know why but seems that in the following call: ... Looks like you have 2 fields that ends up with the same CoveoFieldName (encoded for the index). ... Please check your external ...",
    "FirstSentences" : null
  }