{
    "title" : "Coveo rebuilding index exception: inactivity timeout expired.",
    "uri" : "http://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
    "printableUri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
    "clickUri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
    "excerpt" : "Recently I got the error below when tried to rebuild indexes in the index manager in Sitecore. ... Job started: Index_Update_IndexName=Coveo_master_index|#Exception: System.Reflection.TargetInvocat...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1236,
    "percentScore" : 79.10896,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Coveo rebuilding index exception: inactivity timeout expired.",
      "sysauthor" : "qch1595",
      "sysurihash" : "sMQñoS726IHQJX2b",
      "urihash" : "sMQñoS726IHQJX2b",
      "numberofanswers" : 0,
      "sysuri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160369,
      "questionaskeddatestring" : "·\n            Mar 07, 2017 at 11:23 PM ·",
      "tags" : [ "index", "rebuild", "timeout" ],
      "sysconcepts" : "Exceptions ; Coveo ; Sitecore Cloud ; search token ; query ; logs ; check ; stack trace ; François Lachance-Guillemette ; multiple meanings ; timeout expired ; CoveoSearchProviderException ; invocation ; TargetInvocationException ; Reflection",
      "concepts" : "Exceptions ; Coveo ; Sitecore Cloud ; search token ; query ; logs ; check ; stack trace ; François Lachance-Guillemette ; multiple meanings ; timeout expired ; CoveoSearchProviderException ; invocation ; TargetInvocationException ; Reflection",
      "printableuri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517943372000,
      "permanentid" : "b0a032bbfa39a75cb1d876b7cc0e3c32b692f33cdb0266f42b113f69e2b4",
      "syslanguage" : [ "English" ],
      "transactionid" : 160369,
      "title" : "Coveo rebuilding index exception: inactivity timeout expired.",
      "date" : 1507075200000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "hasanswer" : "false",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "François Lachance-Guillemette \u2666\u2666", "vivekayer", "François Lachance-Guillemette \u2666\u2666", "vivekayer" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5449245,
      "numberofcomments" : 3,
      "size" : 75397,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911579525,
      "acceptedanswers" : 0,
      "syssize" : 75397,
      "sysdate" : 1507075200000,
      "author" : "qch1595",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>Recently I got the error below when tried to rebuild indexes in the index manager in Sitecore.</p> \n<pre><code> Job started: Index_Update_IndexName=Coveo_master_index|#Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Coveo.Framework.Exceptions.CoveoSearchProviderException: Inactivity timeout expired. Not all documents were committed in the allotted time (01:00:00). Aborting the rebuild task.\n    at Coveo.AbstractLayer.Communication.CES.CESCommunication.AreDocumentsCommitted(UInt32 p_ActualTotalCount, UInt32 p_ExpectedTotalCount, String p_SourceName)\n    at Coveo.AbstractLayer.Communication.CES.CESCommunication.<>c__DisplayClass48.<CreateAddedDocumentsPoller>b__47()\n    at Coveo.Framework.Synchronization.Poller.WaitUntilComplete()\n    at Coveo.AbstractLayer.Communication.CES.CESCommunication.StopRebuild(RebuildContext p_Context)\n    at Coveo.SearchProvider.ProviderIndexBase.PerformRebuild(IProviderUpdateContext p_Context, Action`1 p_CrawlerAction)\n    at Coveo.SearchProvider.ProviderIndexBase.Rebuild(IndexingOptions p_IndexingOptions, IProviderUpdateContext p_Context, Action`1 p_CrawlerAction)\n    at Coveo.SearchProvider.ProviderIndex.TryPerformIndexingOperation(IndexingOptions p_IndexingOptions, Action p_Action)\n    at Coveo.SearchProvider.ProviderIndex.Rebuild()\n    --- End of inner exception stack trace ---\n    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\n    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\n    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n    at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)\n    at Sitecore.Jobs.JobRunner.RunMethod(JobArgs args)\n    at (Object , Object[] )\n    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)\n    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)\n    at Sitecore.Jobs.Job.ThreadEntry(Object state)\n</code></pre>\n                </div>",
      "sitemaplastmodified" : 1507075200000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517943372000,
      "questionnumber" : 10685,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "qch1595",
      "sitename" : "Answers",
      "sysrowid" : 5449245,
      "uri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Coveo rebuilding index exception: inactivity timeout expired.",
    "Uri" : "http://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
    "PrintableUri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
    "ClickUri" : "https://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/10685/coveo-rebuilding-index-exception-inactivity-timeou.html",
    "Excerpt" : "Recently I got the error below when tried to rebuild indexes in the index manager in Sitecore. ... Job started: Index_Update_IndexName=Coveo_master_index|#Exception: System.Reflection.TargetInvocat...",
    "FirstSentences" : null
  }