{
    "title" : "Question on Coveo for Sitecore Warning with Discovery Service",
    "uri" : "http://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
    "printableUri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
    "clickUri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
    "excerpt" : "Hello, ... I'm seeing the following warning in the Sitecore log. ... WARN Authentication on CES Discovery service failed. ... Exception: System.Net.WebException Message: The remote server returned ...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1232,
    "percentScore" : 78.98085,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Question on Coveo for Sitecore Warning with Discovery Service",
      "sysauthor" : "chrisarcand",
      "sysurihash" : "aa61hdJA0ao50dTR",
      "urihash" : "aa61hdJA0ao50dTR",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160369,
      "questionaskeddatestring" : "·\n            Aug 26, 2016 at 11:10 AM ·",
      "tags" : [ "coveoforsitecore" ],
      "sysconcepts" : "Sitecore IP Geolocation service ; Client ; Discovery ; String serviceName ; Chris ; remote server ; WebException Message ; Coveo ; EndpointSource ; ResourceConnector ; ExecuteRequest ; HttpWebRequest ; Authentication",
      "concepts" : "Sitecore IP Geolocation service ; Client ; Discovery ; String serviceName ; Chris ; remote server ; WebException Message ; Coveo ; EndpointSource ; ResourceConnector ; ExecuteRequest ; HttpWebRequest ; Authentication",
      "printableuri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517943360000,
      "permanentid" : "faad907045c5813162f361e530836cfc8e83b29a1c83048e4770ed34d1c8",
      "syslanguage" : [ "English" ],
      "transactionid" : 160369,
      "title" : "Question on Coveo for Sitecore Warning with Discovery Service",
      "date" : 1506470400000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "Dominic Berube" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "François Lachance-Guillemette \u2666\u2666" ],
      "hasacceptedanswer" : "true",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5449230,
      "numberofcomments" : 1,
      "size" : 72226,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911579510,
      "acceptedanswers" : 1,
      "syssize" : 72226,
      "sysdate" : 1506470400000,
      "author" : "chrisarcand",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>Hello,</p> \n<p>I'm seeing the following warning in the Sitecore log.</p> \n<p>WARN Authentication on CES Discovery service failed. Exception: System.Net.WebException Message: The remote server returned an error: (403) Forbidden. Source: System at System.Net.HttpWebRequest.GetResponse() at Sitecore.CES.Client.WebClient.ExecuteRequest(String requestUri) at Sitecore.CES.Client.ResourceConnector`1.Request(String endpoint, Object[] parameters) at Sitecore.CES.Discovery.EndpointSource.GetEndpoint(String serviceName)</p> \n<p>Just curious what could be causing this.</p> \n<p>Everything seems to be working otherwise.</p> \n<p>Thanks, Chris </p>\n                </div>",
      "sitemaplastmodified" : 1506470400000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517943360000,
      "questionnumber" : 8821,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "chrisarcand",
      "sitename" : "Answers",
      "sysrowid" : 5449230,
      "uri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "Question on Coveo for Sitecore Warning with Discovery Service",
    "Uri" : "http://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
    "PrintableUri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
    "ClickUri" : "https://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/8821/question-on-coveo-for-sitecore-warning-with-discov.html",
    "Excerpt" : "Hello, ... I'm seeing the following warning in the Sitecore log. ... WARN Authentication on CES Discovery service failed. ... Exception: System.Net.WebException Message: The remote server returned ...",
    "FirstSentences" : null
  }