{
    "title" : "contextDatabase excpetion after installing Coveo for Sitecore",
    "uri" : "http://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
    "printableUri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
    "clickUri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
    "uniqueId" : "42.4247$http://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
    "excerpt" : "Description:An unhandled exception occurred during the execution of the current web request. ... Please review the stack trace for more information about the error and where it originated in the code.",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1206,
    "percentScore" : 78.143005,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "contextDatabase excpetion after installing Coveo for Sitecore",
      "sysauthor" : "qch1595",
      "sysurihash" : "cBq3ÒMTuepG09Kni",
      "urihash" : "cBq3ÒMTuepG09Kni",
      "numberofanswers" : 1,
      "sysuri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
      "sysprintableuri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
      "sitemappriority" : 0.1,
      "systransactionid" : 160367,
      "questionaskeddatestring" : "∑\n            Jul 19, 2017 at 07:43 PM ∑",
      "tags" : [ "contextdatabase" ],
      "sysconcepts" : "exception ; web request ; stack ; execution ; Sitecore ; Database contextDatabase ; Coveo ; InvalidOperationException ; TargetInvocationException ; DefaultImplItemRepository ; Dependencies",
      "concepts" : "exception ; web request ; stack ; execution ; Sitecore ; Database contextDatabase ; Coveo ; InvalidOperationException ; TargetInvocationException ; DefaultImplItemRepository ; Dependencies",
      "printableuri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
      "documenttype" : "WebPage",
      "sysindexeddate" : 1517943241000,
      "permanentid" : "fee5495f8997108373f4aee35acf7e839236e5c298accb9a9b30677042ff",
      "syslanguage" : [ "English" ],
      "transactionid" : 160367,
      "title" : "contextDatabase excpetion after installing Coveo for Sitecore",
      "date" : 1500508800000,
      "objecttype" : "Answers",
      "sitemapchangefrequency" : "Monthly",
      "answerauthor" : [ "qch1595" ],
      "hasanswer" : "true",
      "audience" : [ "Administrator", "Developer" ],
      "commentauthor" : [ "qch1595", "FranÁois Lachance-Guillemette \u2666\u2666" ],
      "hasacceptedanswer" : "false",
      "sourcetype" : "Sitemap",
      "sysconnectortype" : "SitemapCrawler",
      "rowid" : 5449072,
      "numberofcomments" : 1,
      "size" : 79101,
      "sysdocumenttype" : "WebPage",
      "questionvotes" : 0,
      "clickableuri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
      "syssource" : "AnswersCloud",
      "orderingid" : 212384744911579352,
      "acceptedanswers" : 0,
      "syssize" : 79101,
      "sysdate" : 1500508800000,
      "author" : "qch1595",
      "source" : "AnswersCloud",
      "questionbodyhtml" : "<div class=\"question-body\">\n                <p>\n<p>We have Sitecore 8.2.1. After I installed Coveo for Sitecore 4.0(1461) without any errors, I could not login to Sitecore. I got the error below:</p>\n<pre>Server Error in '/' Application.<br><em>contextDatabase<br></em><strong>Description:</strong>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.<br><strong>Exception Details:</strong>System.InvalidOperationException: contextDatabase<br><strong>Source Error:</strong><code>An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code><br><strong>Stack Trace:<br></strong><code><pre>[InvalidOperationException: contextDatabase]\n   Sitecore.Forms.Core.Dependencies.DefaultImplItemRepository..ctor(Database contextDatabase, Database masterDatabase) +103<br></code><code>[TargetInvocationException: Exception has been thrown by the target of an invocation.]\n   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0\n   System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +420\n   Sitecore.Reflection.ReflectionUtil.CreateObject(Type type, Object[] parameters) +119\n   Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +119\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +165\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72\n   Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert) +619\n   Sitecore.Configuration.DefaultFactory.CreateFromReference(XmlNode configNode, String[] parameters, Boolean assert) +170\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +118\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72\n   Sitecore.Configuration.DefaultFactory.GetInnerObject(XmlNode paramNode, String[] parameters, Boolean assert) +110\n   Sitecore.Configuration.DefaultFactory.GetConstructorParameters(XmlNode configNode, String[] parameters, Boolean assert) +163\n   Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +105\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +165\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72\n   Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert) +619\n   Sitecore.Configuration.DefaultFactory.CreateFromReference(XmlNode configNode, String[] parameters, Boolean assert) +170\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +118\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert) +72\n   Sitecore.Configuration.DefaultFactory.GetInnerObject(XmlNode paramNode, String[] parameters, Boolean assert) +110\n   Sitecore.Configuration.DefaultFactory.GetConstructorParameters(XmlNode configNode, String[] parameters, Boolean assert) +163\n   Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert) +105\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper) +165\n   Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, Boolean assert) +68\n   Sitecore.Events.EventSubscribers.Add(String eventName, XmlNode configNode) +545\n   Sitecore.Events.Event.GetConfigSubscribers() +563\n   Sitecore.Events.Event.RaiseEvent(String eventName, Object[] parameters) +373\n   Sitecore.Security.UserProfile.RaiseUserUpdatedEvent() +82\n   Sitecore.Security.SecurityUtil.SetUserDigestCredentials(User user, String credentials, String credentialsWithoutDomain) +126\n   Sitecore.Security.SitecoreMembershipProvider.ValidateUser(String username, String password) +208\n   Sitecore.Security.Authentication.AuthenticationHelper.ValidateUser(String userName, String password) +82\n   Sitecore.Security.Authentication.MembershipAuthenticationProvider.Login(String userName, String password, Boolean persistent) +94\n   Sitecore.sitecore.login.Default.Login() +95\n   Sitecore.sitecore.login.Default.LoginClicked(Object sender, EventArgs e) +50\n   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +11762653\n   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +150\n   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +6016</code></pre>\n<p><code></code></p> \n<p>\n                </div>",
      "sitemaplastmodified" : 1500508800000,
      "collection" : "default",
      "syssourcetype" : "Sitemap",
      "indexeddate" : 1517943241000,
      "questionnumber" : 12089,
      "connectortype" : "SitemapCrawler",
      "filetype" : "html",
      "sysclickableuri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
      "sysfiletype" : "html",
      "language" : [ "English" ],
      "sitemapparenturl" : "http://answers.coveo.com/questions/1.xml",
      "questionauthor" : "qch1595",
      "sitename" : "Answers",
      "sysrowid" : 5449072,
      "uri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "contextDatabase excpetion after installing Coveo for Sitecore",
    "Uri" : "http://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
    "PrintableUri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
    "ClickUri" : "https://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
    "UniqueId" : "42.4247$http://answers.coveo.com/questions/12089/contextdatabase-excpetion-after-installing-coveo-f.html",
    "Excerpt" : "Description:An unhandled exception occurred during the execution of the current web request. ... Please review the stack trace for more information about the error and where it originated in the code.",
    "FirstSentences" : null
  }