{
    "title" : "Unable to create Cloud Org from Salesforce",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA132000000GwXM",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
    "excerpt" : "When attempting to create a cloud org from within your Salesfroce instance, this message is returned: ... An unexpected error occurred while creating your organization. ... Contact Coveo Support fo...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1393,
    "percentScore" : 83.98312,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Unable to create Cloud Org from Salesforce",
      "sfsummary" : "when attempting to create a cloud org from within my Salesfroce instance, an error is returned.",
      "sysurihash" : "OXyrwNjlnbWkSTkH",
      "urihash" : "OXyrwNjlnbWkSTkH",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Unable to create Cloud Org from Salesforce\" uri=\"https://na61.salesforce.com/kA132000000GwXM\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "Reset the Password using the link &quot;<a href=\"https://cloudplatform.coveo.com/forgotpassword\" target=\"_blank\">Forgot your password?</a>&quot; <br>Retry creating an org from Salesforce.<br><br>Otherwise, contact Coveo Support",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
      "sflastpublisheddate" : 1482865582000,
      "systransactionid" : 161138,
      "sfurlname" : "1718",
      "sfsystemmodstamp" : 1517485622000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Coveo for Salesforce V2, Cloud Platform V1",
      "sysconcepts" : "coveo ; error occurred ; cloud org ; cloudplatform ; username ; account ; Salesfroce ; Resolution ; Environment",
      "sfkbversionnumber" : "3",
      "concepts" : "coveo ; error occurred ; cloud org ; cloudplatform ; username ; account ; Salesfroce ; Resolution ; Environment",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka132000000LKYQAA4",
      "sysindexeddate" : 1518187526000,
      "sfknowledgearticleid" : "kA132000000GwXMCA0",
      "sfcreatedbyid" : "00532000004beO8AAI",
      "sfconnectorc" : "N/A",
      "permanentid" : "0fd204019576097cec27863ace1979977c65569745b9dfb9dc3c4b926e0c",
      "syslanguage" : [ "English" ],
      "transactionid" : 161138,
      "sfisvisibleinprm" : "true",
      "title" : "Unable to create Cloud Org from Salesforce",
      "sfversionnumber" : 3,
      "sfarticlenumber" : "000001718",
      "date" : 1517485622000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA132000000GwXM\"], \"sflastmodifiedbyname\": [\"Frederic Cote\"], \"kav_coveo_version__c__html_stripped\": [\"Coveo for Salesforce V2, Cloud Platform V1\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Cloud Platform;All|Salesforce\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000004beO8AAI\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00532000004beO8AAI\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Unable to create Cloud Org from Salesforce\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000004beO8AAI\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Unable to create Cloud Org from Salesforce\\\" uri=\\\"https://na61.salesforce.com/kA132000000GwXM\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Unable to create Cloud Org from Salesforce\"], \"kav_isvisibleincsp\": [true], \"sfcreateddate\": [1482865554], \"hashtmlversion\": [true], \"kav_versionnumber\": [3], \"sfcreatedbyname\": [\"Guillaume Minero\"], \"sflastpublisheddate\": [1482865582], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"The account mapped to my username is locked out from cloudplatform.coveo.com \\n \\n \\u00a0\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1482865582], \"sfsystemmodstamp\": [1517485622], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Cloud Platform;Salesforce\"], \"kav_resolution__c__html_stripped\": [\"Reset the Password using the link \\\" Forgot your password? \\\"\\u00a0 \\n Retry creating an org from Salesforce. \\n \\n Otherwise, contact Coveo Support\"], \"clickableuri\": [\"https://na61.salesforce.com/kA132000000GwXM\"], \"sftitle\": [\"Unable to create Cloud Org from Salesforce\"], \"kav_owner.id\": [\"00532000004beO8AAI\"], \"sfbuildc\": [\"All\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA132000000GwXMCA0\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"The account mapped to my username is locked out from cloudplatform.coveo.com<br><br>\\u00a0\"], \"sfislatestversion\": [true], \"sfcausec\": [\"The account mapped to my username is locked out from cloudplatform.coveo.com<br><br>\\u00a0\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"1718\"], \"ka_id\": [\"kA132000000GwXMCA0\"], \"kav_datacategoryselections.datacategoryname\": [\"Cloud_Platform;Salesforce;Configuration\"], \"coveo_url\": [\"https://na61.salesforce.com/kA132000000GwXM\"], \"kav_urlname\": [\"1718\"], \"kav_dc_expanded_product\": [\"All;All|Cloud Platform;All|Salesforce\"], \"foldingcollection\": [\"1b6f069192a258385195525b13e2fc2fc3495942d9c6835a75f2efb4afa2\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> When attempting to create a cloud org from within your\\u00a0Salesfroce instance, this message is returned:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nAn unexpected error occurred while creating your organization. Contact Coveo Support for more information.</pre>\\n<br>\\u00a0</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1482865582</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td>All</td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> The account mapped to my username is locked out from cloudplatform.coveo.com<br><br>\\u00a0</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> Reset the Password using the link &quot;<a href=\\\"https://cloudplatform.coveo.com/forgotpassword\\\" target=\\\"_blank\\\">Forgot your password?</a>&quot;\\u00a0<br>Retry creating an org from Salesforce.<br><br>Otherwise, contact Coveo Support</div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00532000004beO8AAI\"], \"kav_description__c__html_stripped\": [\"When attempting to create a cloud org from within your\\u00a0Salesfroce instance, this message is returned: \\n \\u00a0\\n \\nAn unexpected error occurred while creating your organization. Contact Coveo Support for more information. \\n \\n \\u00a0\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA132000000GwXMCA0\"], \"sfknowledgearticleid\": [\"kA132000000GwXMCA0\"], \"sfownername\": [\"Guillaume Minero\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1482865554], \"kav_build__c\": [\"All\"], \"language\": [\"English\"], \"coveo_foldingchild\": [\"0bea7c05849f67f7d7899f99c19f312a10ff270dbbab03de505e2b77ee18\"], \"sfownerid\": [\"00532000004beO8AAI\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1517485622], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Guillaume Minero\"], \"sfcoveoversionc\": [\"Coveo for Salesforce V2, Cloud Platform V1\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"CAD\"], \"sfisdeleted\": [false], \"extractedsize\": [1140], \"size\": [3635], \"kav_summary\": [\"when attempting to create a cloud org from within my Salesfroce instance, an error is returned.\"], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"When attempting to create a cloud org from within your\\u00a0Salesfroce instance, this message is returned:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nAn unexpected error occurred while creating your organization. Contact Coveo Support for more information.</pre>\\n<br>\\u00a0\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1482865582], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka132000000LKYQAA4\"], \"kav_currencyisocode\": [\"CAD\"], \"foldingparent\": [\"0bea7c05849f67f7d7899f99c19f312a10ff270dbbab03de505e2b77ee18\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"500320000122Uh4AAE\"], \"sfkbversionnumber\": [3], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"Reset the Password using the link &quot;<a href=\\\"https://cloudplatform.coveo.com/forgotpassword\\\" target=\\\"_blank\\\">Forgot your password?</a>&quot;\\u00a0<br>Retry creating an org from Salesforce.<br><br>Otherwise, contact Coveo Support\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000pvyKAAQ;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000pvyHAAQ;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000pvyGAAQ\"], \"kav_id\": [\"ka132000000LKYQAA4\"], \"sfresolutionc\": [\"Reset the Password using the link &quot;<a href=\\\"https://cloudplatform.coveo.com/forgotpassword\\\" target=\\\"_blank\\\">Forgot your password?</a>&quot;\\u00a0<br>Retry creating an org from Salesforce.<br><br>Otherwise, contact Coveo Support\"], \"foldingchild\": [\"0bea7c05849f67f7d7899f99c19f312a10ff270dbbab03de505e2b77ee18\"], \"sfsummary\": [\"when attempting to create a cloud org from within my Salesfroce instance, an error is returned.\"], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1517485622], \"kav_summary__html_stripped\": [\"when attempting to create a cloud org from within my Salesfroce instance, an error is returned.\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Cloud Platform;Salesforce\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2;2\"], \"concepts\": [\"coveo ; error occurred ; cloud org ; cloudplatform ; username ; account ; Salesfroce ; Resolution ; Environment\"], \"sfkbid\": [\"kA132000000GwXMCA0\"], \"kav_firstpublisheddate\": [1473800846], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"1b6f069192a258385195525b13e2fc2fc3495942d9c6835a75f2efb4afa2\"], \"sffirstpublisheddate\": [1473800846], \"sflastmodifieddate\": [1482865582], \"kav_coveo_version__c\": [\"Coveo for Salesforce V2, Cloud Platform V1\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000003q7JgAAI\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Guillaume Minero\"], \"sfarticlenumber\": [\"000001718\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o32000000pvyKAAQ;02o32000000pvyHAAQ;02o32000000pvyGAAQ\"], \"kav_description__c\": [\"When attempting to create a cloud org from within your\\u00a0Salesfroce instance, this message is returned:<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nAn unexpected error occurred while creating your organization. Contact Coveo Support for more information.</pre>\\n<br>\\u00a0\"], \"kav_validationstatus\": [\"Reviewed\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka132000000LKYQAA4\"], \"kav_articlenumber__stripped\": [\"1718\"], \"sfversionnumber\": [3], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"coveo_foldingparent\": [\"0bea7c05849f67f7d7899f99c19f312a10ff270dbbab03de505e2b77ee18\"], \"collection\": [\"default\"], \"sfsourceid\": [\"500320000122Uh4AAE\"], \"date\": [1517485622], \"kav_lastmodifiedby.id\": [\"00560000003q7JgAAI\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Product;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000003q7JgAAI\"], \"kav_lastmodifiedby.name\": [\"Frederic Cote\"], \"kav_articlenumber\": [\"000001718\"], \"permanentid\": [\"0fd204019576097cec27863ace1979977c65569745b9dfb9dc3c4b926e0c\"]}",
      "sfbuildc" : "All",
      "sflastmodifiedbyid" : "00560000003q7JgAAI",
      "syssfownerid" : "00532000004beO8AAI",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Unable to create Cloud Org from Salesforce",
      "rowid" : 5492298,
      "syssfcreatedbyid" : "00532000004beO8AAI",
      "sfdescriptionc" : "When attempting to create a cloud org from within your Salesfroce instance, this message is returned:<br> \n<pre class=\"ckeditor_codeblock\">\nAn unexpected error occurred while creating your organization. Contact Coveo Support for more information.</pre>\n<br> ",
      "size" : 3635,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1482865554000,
      "sfsourceid" : "500320000122Uh4AAE",
      "clickableuri" : "https://na61.salesforce.com/kA132000000GwXM",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00532000004beO8AAI",
      "orderingid" : 212384990660371106,
      "sfpublishstatus" : "Online",
      "syssize" : 3635,
      "sysdate" : 1517485622000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Unable to create Cloud Org from Salesforce\" uri=\"https://na61.salesforce.com/kA132000000GwXM\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "CAD",
      "sfkbid" : "kA132000000GwXMCA0",
      "sfcausec" : "The account mapped to my username is locked out from cloudplatform.coveo.com<br><br> ",
      "sfdcexpandedproduct" : "All;All|Cloud Platform;All|Salesforce",
      "syssfcreateddate" : 1482865554000,
      "sflastmodifieddate" : 1482865582000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Frederic Cote",
      "collection" : "default",
      "sfdcproduct" : [ "Cloud Platform", "Salesforce" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187526000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Guillaume Minero",
      "sysclickableuri" : "https://na61.salesforce.com/kA132000000GwXM",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1473800846000,
      "sfownername" : "Guillaume Minero",
      "sitename" : "Community",
      "sysrowid" : 5492298,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Unable to create Cloud Org from Salesforce",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA132000000GwXM",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000GwXMCA0/language:en_US",
    "Excerpt" : "When attempting to create a cloud org from within your Salesfroce instance, this message is returned: ... An unexpected error occurred while creating your organization. ... Contact Coveo Support fo...",
    "FirstSentences" : null
  }