{
    "title" : "Issue about ssl in Usage Analytics setup in an hybrid environment.",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA132000000Xcdw",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
    "excerpt" : "When you see this stack trace after trying to enable the analytics on a hybrid setup (Coveo Enterprise Search On-Premise and the Usage Analytics on Cloud) ... System.Net.WebException: The underlyin...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1345,
    "percentScore" : 82.52349,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Issue about ssl in Usage Analytics setup in an hybrid environment.",
      "sfsummary" : "Error while trying to enable the cloud usage analytics with an on-premise setup because of the SSL Certificates.",
      "sysurihash" : "L1fwMNpaK2nHL9b3",
      "urihash" : "L1fwMNpaK2nHL9b3",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Issue about ssl in Usage Analytics setup in an hybrid environment.\" uri=\"https://na61.salesforce.com/kA132000000Xcdw\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "To test this you can try to reach out this <a href=\"https://usageanalytics.coveo.com/.\" target=\"_blank\">page</a><br><br>You will see if the certificates were authorize in your environment.<br><br>To resolve this simply add the *.coveo.com ssl certificates in your environment and authorize them. <br><br>Here is an article on <a href=\"https://www.digicert.com/ssl-certificate-installation-microsoft-iis-8.htm\" target=\"_blank\">digicert</a> on how you can manage and add those certificate.",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
      "sflastpublisheddate" : 1496851717000,
      "systransactionid" : 161139,
      "sfurlname" : "2316",
      "sfsystemmodstamp" : 1516362333000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Usage Analytics",
      "sysconcepts" : "SslState ; certificates ; exception ; coveo ; analytics ; Int32 count ; ProtocolToken message ; validation procedure ; trust relationship ; underlying connection ; Search On-Premise ; StartReceiveBlob ; ProcessReceivedBlob ; StartSendAuthResetSignal ; AuthenticationException",
      "sfkbversionnumber" : "1",
      "concepts" : "SslState ; certificates ; exception ; coveo ; analytics ; Int32 count ; ProtocolToken message ; validation procedure ; trust relationship ; underlying connection ; Search On-Premise ; StartReceiveBlob ; ProcessReceivedBlob ; StartSendAuthResetSignal ; AuthenticationException",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka132000000bqqIAAQ",
      "sysindexeddate" : 1518187563000,
      "sfknowledgearticleid" : "kA132000000XcdwCAC",
      "sfcreatedbyid" : "00532000005I7BbAAK",
      "sfconnectorc" : "N/A",
      "permanentid" : "390dcd6a341ed25ad57c929e159fd9b5c7e6d5f99dd54db3af20b667a27c",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "Issue about ssl in Usage Analytics setup in an hybrid environment.",
      "sfversionnumber" : 1,
      "sfarticlenumber" : "000002316",
      "date" : 1516362333000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA132000000Xcdw\"], \"sflastmodifiedbyname\": [\"Karel Mpungi\"], \"kav_coveo_version__c__html_stripped\": [\"Usage Analytics\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Usage Analytics\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005I7BbAAK\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00532000005I7BbAAK\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Issue about ssl in Usage Analytics setup in an hybrid environment.\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000005I7BbAAK\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Issue about ssl in Usage Analytics setup in an hybrid environment.\\\" uri=\\\"https://na61.salesforce.com/kA132000000Xcdw\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Issue about ssl in Usage Analytics setup in an hybrid environment.\"], \"kav_isvisibleincsp\": [true], \"sfcreateddate\": [1495656593], \"hashtmlversion\": [true], \"kav_versionnumber\": [1], \"sfcreatedbyname\": [\"Marc-Antoine Gosselin\"], \"sflastpublisheddate\": [1496851717], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"This is cause by some missing SSL certificates in the environment.\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1496851717], \"sfsystemmodstamp\": [1516362333], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Usage Analytics\"], \"kav_resolution__c__html_stripped\": [\"To test this you can try to reach out this  page \\n \\n You will see if the certificates were authorize in your environment. \\n \\n To resolve this simply add the *.coveo.com ssl certificates in your environment and authorize them.\\u00a0 \\n \\n Here is an article on  digicert  on how you can manage and add those certificate.\"], \"clickableuri\": [\"https://na61.salesforce.com/kA132000000Xcdw\"], \"sftitle\": [\"Issue about ssl in Usage Analytics setup in an hybrid environment.\"], \"kav_owner.id\": [\"00532000005I7BbAAK\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA132000000XcdwCAC\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"This is cause by some missing SSL certificates in the environment.\"], \"sfislatestversion\": [true], \"sfcausec\": [\"This is cause by some missing SSL certificates in the environment.\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"2316\"], \"ka_id\": [\"kA132000000XcdwCAC\"], \"kav_datacategoryselections.datacategoryname\": [\"Usage_Analytics;Configuration\"], \"coveo_url\": [\"https://na61.salesforce.com/kA132000000Xcdw\"], \"kav_urlname\": [\"2316\"], \"kav_dc_expanded_product\": [\"All;All|Usage Analytics\"], \"foldingcollection\": [\"c0a229d1c71afe5a742bfae9387dfb44ac601c3ee353258463e6b57b8aad\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> When you see this stack trace after trying to enable the analytics on a hybrid setup (Coveo Enterprise Search On-Premise and the Usage Analytics on Cloud)<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nSystem.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---&gt; System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at\\u00a0System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at\\u00a0System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result) at\\u00a0System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size) at\\u00a0System.Net.ConnectStream.WriteHeaders(Boolean async) --- End of inner exception stack trace --- at\\u00a0System.Net.HttpWebRequest.GetRequestStream(TransportContext&amp; context) at\\u00a0System.Net.HttpWebRequest.GetRequestStream() at Coveo.CES.Web.Search.CloudPushService.CloudPushService.PushEvent(String p_RequestUri, String p_VisitorID, String p_BrowserIpAddress, String p_EventAsJson, String p_CLOUD_UA_VISITOR_COOKIE_NAME, Boolean&amp; p_OutVisitorCookieUpdatedValue, String&amp; p_OutException)</pre></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1496851717</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> This is cause by some missing SSL certificates in the environment.</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> To test this you can try to reach out this <a href=\\\"https://usageanalytics.coveo.com/.\\\" target=\\\"_blank\\\">page</a><br><br>You will see if the certificates were authorize in your environment.<br><br>To resolve this simply add the *.coveo.com ssl certificates in your environment and authorize them.\\u00a0<br><br>Here is an article on <a href=\\\"https://www.digicert.com/ssl-certificate-installation-microsoft-iis-8.htm\\\" target=\\\"_blank\\\">digicert</a> on how you can manage and add those certificate.</div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00532000005I7BbAAK\"], \"kav_description__c__html_stripped\": [\"When you see this stack trace after trying to enable the analytics on a hybrid setup (Coveo Enterprise Search On-Premise and the Usage Analytics on Cloud) \\n \\u00a0\\n \\nSystem.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at\\u00a0System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at\\u00a0System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result) at\\u00a0System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size) at\\u00a0System.Net.ConnectStream.WriteHeaders(Boolean async) --- End of inner exception stack trace --- at\\u00a0System.Net.HttpWebRequest.GetRequestStream(TransportContext& context) at\\u00a0System.Net.HttpWebRequest.GetRequestStream() at Coveo.CES.Web.Search.CloudPushService.CloudPushService.PushEvent(String p_RequestUri, String p_VisitorID, String p_BrowserIpAddress, String p_EventAsJson, String p_CLOUD_UA_VISITOR_COOKIE_NAME, Boolean& p_OutVisitorCookieUpdatedValue, String& p_OutException)\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA132000000XcdwCAC\"], \"sfknowledgearticleid\": [\"kA132000000XcdwCAC\"], \"sfownername\": [\"Marc-Antoine Gosselin\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1495656593], \"language\": [\"English\"], \"coveo_foldingchild\": [\"20bc8e175253e9f54459447bcb0af32d417308803ad8bccdf956997b2d78\"], \"sfownerid\": [\"00532000005I7BbAAK\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1516362333], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Marc-Antoine Gosselin\"], \"sfcoveoversionc\": [\"Usage Analytics\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"CAD\"], \"sfisdeleted\": [false], \"extractedsize\": [6790], \"size\": [9257], \"kav_summary\": [\"Error while trying to enable the cloud usage analytics with an on-premise setup because of the SSL Certificates.\"], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"When you see this stack trace after trying to enable the analytics on a hybrid setup (Coveo Enterprise Search On-Premise and the Usage Analytics on Cloud)<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nSystem.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---&gt; System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at\\u00a0System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at\\u00a0System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result) at\\u00a0System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size) at\\u00a0System.Net.ConnectStream.WriteHeaders(Boolean async) --- End of inner exception stack trace --- at\\u00a0System.Net.HttpWebRequest.GetRequestStream(TransportContext&amp; context) at\\u00a0System.Net.HttpWebRequest.GetRequestStream() at Coveo.CES.Web.Search.CloudPushService.CloudPushService.PushEvent(String p_RequestUri, String p_VisitorID, String p_BrowserIpAddress, String p_EventAsJson, String p_CLOUD_UA_VISITOR_COOKIE_NAME, Boolean&amp; p_OutVisitorCookieUpdatedValue, String&amp; p_OutException)</pre>\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1496851717], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka132000000bqqIAAQ\"], \"kav_currencyisocode\": [\"CAD\"], \"foldingparent\": [\"20bc8e175253e9f54459447bcb0af32d417308803ad8bccdf956997b2d78\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"5003200001Bex07AAB\"], \"sfkbversionnumber\": [1], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"To test this you can try to reach out this <a href=\\\"https://usageanalytics.coveo.com/.\\\" target=\\\"_blank\\\">page</a><br><br>You will see if the certificates were authorize in your environment.<br><br>To resolve this simply add the *.coveo.com ssl certificates in your environment and authorize them.\\u00a0<br><br>Here is an article on <a href=\\\"https://www.digicert.com/ssl-certificate-installation-microsoft-iis-8.htm\\\" target=\\\"_blank\\\">digicert</a> on how you can manage and add those certificate.\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000dw0cAAA;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o32000000dw0dAAA\"], \"kav_id\": [\"ka132000000bqqIAAQ\"], \"sfresolutionc\": [\"To test this you can try to reach out this <a href=\\\"https://usageanalytics.coveo.com/.\\\" target=\\\"_blank\\\">page</a><br><br>You will see if the certificates were authorize in your environment.<br><br>To resolve this simply add the *.coveo.com ssl certificates in your environment and authorize them.\\u00a0<br><br>Here is an article on <a href=\\\"https://www.digicert.com/ssl-certificate-installation-microsoft-iis-8.htm\\\" target=\\\"_blank\\\">digicert</a> on how you can manage and add those certificate.\"], \"foldingchild\": [\"20bc8e175253e9f54459447bcb0af32d417308803ad8bccdf956997b2d78\"], \"sfsummary\": [\"Error while trying to enable the cloud usage analytics with an on-premise setup because of the SSL Certificates.\"], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1516362333], \"kav_summary__html_stripped\": [\"Error while trying to enable the cloud usage analytics with an on-premise setup because of the SSL Certificates.\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Usage Analytics\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2\"], \"concepts\": [\"SslState ; certificates ; exception ; coveo ; analytics ; Int32 count ; ProtocolToken message ; validation procedure ; trust relationship ; underlying connection ; Search On-Premise ; StartReceiveBlob ; ProcessReceivedBlob ; StartSendAuthResetSignal ; AuthenticationException\"], \"sfkbid\": [\"kA132000000XcdwCAC\"], \"kav_firstpublisheddate\": [1496851717], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"c0a229d1c71afe5a742bfae9387dfb44ac601c3ee353258463e6b57b8aad\"], \"sffirstpublisheddate\": [1496851717], \"sflastmodifieddate\": [1496851717], \"kav_coveo_version__c\": [\"Usage Analytics\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Marc-Antoine Gosselin\"], \"sfarticlenumber\": [\"000002316\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o32000000dw0cAAA;02o32000000dw0dAAA\"], \"kav_description__c\": [\"When you see this stack trace after trying to enable the analytics on a hybrid setup (Coveo Enterprise Search On-Premise and the Usage Analytics on Cloud)<br>\\u00a0\\n<pre class=\\\"ckeditor_codeblock\\\">\\nSystem.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---&gt; System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at\\u00a0System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) at\\u00a0System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at\\u00a0System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result) at\\u00a0System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size) at\\u00a0System.Net.ConnectStream.WriteHeaders(Boolean async) --- End of inner exception stack trace --- at\\u00a0System.Net.HttpWebRequest.GetRequestStream(TransportContext&amp; context) at\\u00a0System.Net.HttpWebRequest.GetRequestStream() at Coveo.CES.Web.Search.CloudPushService.CloudPushService.PushEvent(String p_RequestUri, String p_VisitorID, String p_BrowserIpAddress, String p_EventAsJson, String p_CLOUD_UA_VISITOR_COOKIE_NAME, Boolean&amp; p_OutVisitorCookieUpdatedValue, String&amp; p_OutException)</pre>\"], \"kav_validationstatus\": [\"Reviewed\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka132000000bqqIAAQ\"], \"kav_articlenumber__stripped\": [\"2316\"], \"sfversionnumber\": [1], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"coveo_foldingparent\": [\"20bc8e175253e9f54459447bcb0af32d417308803ad8bccdf956997b2d78\"], \"collection\": [\"default\"], \"sfsourceid\": [\"5003200001Bex07AAB\"], \"date\": [1516362333], \"kav_lastmodifiedby.id\": [\"00560000002MKBSAA4\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000002MKBSAA4\"], \"kav_lastmodifiedby.name\": [\"Karel Mpungi\"], \"kav_articlenumber\": [\"000002316\"], \"permanentid\": [\"390dcd6a341ed25ad57c929e159fd9b5c7e6d5f99dd54db3af20b667a27c\"]}",
      "sflastmodifiedbyid" : "00560000002MKBSAA4",
      "syssfownerid" : "00532000005I7BbAAK",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Issue about ssl in Usage Analytics setup in an hybrid environment.",
      "rowid" : 5492759,
      "syssfcreatedbyid" : "00532000005I7BbAAK",
      "sfdescriptionc" : "When you see this stack trace after trying to enable the analytics on a hybrid setup (Coveo Enterprise Search On-Premise and the Usage Analytics on Cloud)<br> \n<pre class=\"ckeditor_codeblock\">\nSystem.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---&gt; System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result) at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size) at System.Net.ConnectStream.WriteHeaders(Boolean async) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetRequestStream(TransportContext&amp; context) at System.Net.HttpWebRequest.GetRequestStream() at Coveo.CES.Web.Search.CloudPushService.CloudPushService.PushEvent(String p_RequestUri, String p_VisitorID, String p_BrowserIpAddress, String p_EventAsJson, String p_CLOUD_UA_VISITOR_COOKIE_NAME, Boolean&amp; p_OutVisitorCookieUpdatedValue, String&amp; p_OutException)</pre>",
      "size" : 9257,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1495656593000,
      "sfsourceid" : "5003200001Bex07AAB",
      "clickableuri" : "https://na61.salesforce.com/kA132000000Xcdw",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00532000005I7BbAAK",
      "orderingid" : 212384990660371558,
      "sfpublishstatus" : "Online",
      "syssize" : 9257,
      "sysdate" : 1516362333000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Issue about ssl in Usage Analytics setup in an hybrid environment.\" uri=\"https://na61.salesforce.com/kA132000000Xcdw\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "CAD",
      "sfkbid" : "kA132000000XcdwCAC",
      "sfcausec" : "This is cause by some missing SSL certificates in the environment.",
      "sfdcexpandedproduct" : "All;All|Usage Analytics",
      "syssfcreateddate" : 1495656593000,
      "sflastmodifieddate" : 1496851717000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Karel Mpungi",
      "collection" : "default",
      "sfdcproduct" : [ "Usage Analytics" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187563000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Marc-Antoine Gosselin",
      "sysclickableuri" : "https://na61.salesforce.com/kA132000000Xcdw",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1496851717000,
      "sfownername" : "Marc-Antoine Gosselin",
      "sitename" : "Community",
      "sysrowid" : 5492759,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Issue about ssl in Usage Analytics setup in an hybrid environment.",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA132000000Xcdw",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA132000000XcdwCAC/language:en_US",
    "Excerpt" : "When you see this stack trace after trying to enable the analytics on a hybrid setup (Coveo Enterprise Search On-Premise and the Usage Analytics on Cloud) ... System.Net.WebException: The underlyin...",
    "FirstSentences" : null
  }