{
    "title" : "Unable to create a new source in Coveo Cloud V2",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA1320000000877",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
    "excerpt" : "Environment ... Cause ... When creating a new source in Coveo Cloud V2, you might get the following error: ... In Google Developers tool, you might see this error: \"message: \"Security provider with...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1251,
    "percentScore" : 79.58755,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Unable to create a new source in Coveo Cloud V2",
      "sysurihash" : "TrrrM2514sjU1NcK",
      "urihash" : "TrrrM2514sjU1NcK",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Unable to create a new source in Coveo Cloud V2\" uri=\"https://na61.salesforce.com/kA1320000000877\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "You can either delete some security provider you don&#39;t use anymore or open a support case so Coveo support will ask the Cloud_ops team to increase the number of security provider in your org.",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
      "sflastpublisheddate" : 1499107964000,
      "systransactionid" : 161139,
      "sfurlname" : "2360",
      "sfsystemmodstamp" : 1509619413000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Cloud Platform",
      "sysconcepts" : "security provider ; org ; id ; Cloud V2 ; Developers tool ; ops ; anymore ; errorCode ; Environment",
      "sfkbversionnumber" : "1",
      "concepts" : "security provider ; org ; id ; Cloud V2 ; Developers tool ; ops ; anymore ; errorCode ; Environment",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka1320000000G8HAAU",
      "sysindexeddate" : 1518187571000,
      "sfknowledgearticleid" : "kA1320000000877CAA",
      "sfcreatedbyid" : "00560000002MKBSAA4",
      "sfconnectorc" : "N/A",
      "permanentid" : "51badda0dd95d4f821d3412e417799222f19d804a9859e9dd125bd0298a0",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "Unable to create a new source in Coveo Cloud V2",
      "sfversionnumber" : 1,
      "sfarticlenumber" : "000002360",
      "date" : 1509619413000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA1320000000877\"], \"sflastmodifiedbyname\": [\"Karel Mpungi\"], \"kav_coveo_version__c__html_stripped\": [\"Cloud Platform\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Cloud Platform\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00560000002MKBSAA4\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Unable to create a new source in Coveo Cloud V2\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Unable to create a new source in Coveo Cloud V2\\\" uri=\\\"https://na61.salesforce.com/kA1320000000877\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Unable to create a new source in Coveo Cloud V2\"], \"kav_isvisibleincsp\": [true], \"hashtmlversion\": [true], \"kav_versionnumber\": [1], \"sfcreatedbyname\": [\"Karel Mpungi\"], \"sflastpublisheddate\": [1499107964], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"When creating a new source in Coveo Cloud V2, you might get the following error: \\n \\n  \\n \\n In Google Developers tool, you might see this error:\\n \\n\\\"message: \\\"Security provider with id 'MICROSOFT_DYNAMICS-[IDNUMBER]-[ORG ID]' does not exist. \\\"\\n\\\"errorCode: \\\"INVALID_SOURCE_CONFIGURATION\\\" \\n \\n This is simply because the number of security provider limit was reached on this org.By default, this number is 15.\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1499107964], \"sfsystemmodstamp\": [1509619413], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Cloud Platform\"], \"kav_resolution__c__html_stripped\": [\"You can either delete some security provider you don't use anymore or open a support case so Coveo support will ask the Cloud_ops team to increase the number of security provider in your org.\"], \"clickableuri\": [\"https://na61.salesforce.com/kA1320000000877\"], \"sftitle\": [\"Unable to create a new source in Coveo Cloud V2\"], \"kav_owner.id\": [\"00560000002MKBSAA4\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA1320000000877CAA\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"When creating a new source in Coveo Cloud V2, you might get the following error:<br><br><img alt=\\\"User-added image\\\" height=\\\"285\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka1320000000G8H&amp;feoid=00N32000002zy1O&amp;refid=0EM32000000Ai3O\\\" width=\\\"500\\\"></img><br><br>In Google Developers tool, you might see this error:\\n<pre class=\\\"ckeditor_codeblock\\\">\\n&quot;message: &quot;Security provider with id &#39;MICROSOFT_DYNAMICS-[IDNUMBER]-[ORG ID]&#39; does not exist. &quot;\\n&quot;errorCode: &quot;INVALID_SOURCE_CONFIGURATION&quot;</pre>\\n<br>This is simply because the number of security provider limit was reached on this org.By default, this number is 15.\"], \"sfislatestversion\": [true], \"sfcausec\": [\"When creating a new source in Coveo Cloud V2, you might get the following error:<br><br><img alt=\\\"User-added image\\\" height=\\\"285\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka1320000000G8H&amp;feoid=00N32000002zy1O&amp;refid=0EM32000000Ai3O\\\" width=\\\"500\\\"></img><br><br>In Google Developers tool, you might see this error:\\n<pre class=\\\"ckeditor_codeblock\\\">\\n&quot;message: &quot;Security provider with id &#39;MICROSOFT_DYNAMICS-[IDNUMBER]-[ORG ID]&#39; does not exist. &quot;\\n&quot;errorCode: &quot;INVALID_SOURCE_CONFIGURATION&quot;</pre>\\n<br>This is simply because the number of security provider limit was reached on this org.By default, this number is 15.\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"2360\"], \"ka_id\": [\"kA1320000000877CAA\"], \"kav_datacategoryselections.datacategoryname\": [\"Cloud_Platform;Configuration\"], \"coveo_url\": [\"https://na61.salesforce.com/kA1320000000877\"], \"kav_urlname\": [\"2360\"], \"kav_dc_expanded_product\": [\"All;All|Cloud Platform\"], \"foldingcollection\": [\"e3ac12eb5515e25af6e2242ec8bdb2eb0447dbe5b9d1391d0970f2f022c2\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> How to deal with a situation when you cannot create a new source in Coveo Cloud V2</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1499107964</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> When creating a new source in Coveo Cloud V2, you might get the following error:<br><br><img alt=\\\"User-added image\\\" height=\\\"285\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka1320000000G8H&amp;feoid=00N32000002zy1O&amp;refid=0EM32000000Ai3O\\\" width=\\\"500\\\"></img><br><br>In Google Developers tool, you might see this error:\\n<pre class=\\\"ckeditor_codeblock\\\">\\n&quot;message: &quot;Security provider with id &#39;MICROSOFT_DYNAMICS-[IDNUMBER]-[ORG ID]&#39; does not exist. &quot;\\n&quot;errorCode: &quot;INVALID_SOURCE_CONFIGURATION&quot;</pre>\\n<br>This is simply because the number of security provider limit was reached on this org.By default, this number is 15.</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> You can either delete some security provider you don&#39;t use anymore or open a support case so Coveo support will ask the Cloud_ops team to increase the number of security provider in your org.</div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00560000002MKBSAA4\"], \"kav_description__c__html_stripped\": [\"How to deal with a situation when you cannot create a new source in Coveo Cloud V2\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA1320000000877CAA\"], \"sfknowledgearticleid\": [\"kA1320000000877CAA\"], \"sfownername\": [\"Karel Mpungi\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"How to deal with a situation when you cannot create a new source in Coveo Cloud V2\"], \"kav_createddate\": [1498160319], \"language\": [\"English\"], \"coveo_foldingchild\": [\"f876b80bd6bf37b498d2d72950bb60471fa79e87fb5ae910942b5d58a48b\"], \"sfownerid\": [\"00560000002MKBSAA4\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1509619413], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Karel Mpungi\"], \"sfcoveoversionc\": [\"Cloud Platform\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"USD\"], \"sfisdeleted\": [false], \"extractedsize\": [1634], \"size\": [3823], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"How to deal with a situation when you cannot create a new source in Coveo Cloud V2\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1499107964], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka1320000000G8HAAU\"], \"kav_currencyisocode\": [\"USD\"], \"foldingparent\": [\"f876b80bd6bf37b498d2d72950bb60471fa79e87fb5ae910942b5d58a48b\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"5003200001CoUozAAF\"], \"sfkbversionnumber\": [1], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"You can either delete some security provider you don&#39;t use anymore or open a support case so Coveo support will ask the Cloud_ops team to increase the number of security provider in your org.\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o320000004ce9AAA;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o320000004ce8AAA\"], \"kav_id\": [\"ka1320000000G8HAAU\"], \"sfresolutionc\": [\"You can either delete some security provider you don&#39;t use anymore or open a support case so Coveo support will ask the Cloud_ops team to increase the number of security provider in your org.\"], \"foldingchild\": [\"f876b80bd6bf37b498d2d72950bb60471fa79e87fb5ae910942b5d58a48b\"], \"sfcreateddate\": [1498160319], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1509619413], \"kav_summary__html_stripped\": [\"\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Cloud Platform\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2\"], \"concepts\": [\"security provider ; org ; id ; Cloud V2 ; Developers tool ; ops ; anymore ; errorCode ; Environment\"], \"sfkbid\": [\"kA1320000000877CAA\"], \"kav_firstpublisheddate\": [1499107964], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"e3ac12eb5515e25af6e2242ec8bdb2eb0447dbe5b9d1391d0970f2f022c2\"], \"sffirstpublisheddate\": [1499107964], \"sflastmodifieddate\": [1499107964], \"kav_coveo_version__c\": [\"Cloud Platform\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Karel Mpungi\"], \"sfarticlenumber\": [\"000002360\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o320000004ce9AAA;02o320000004ce8AAA\"], \"kav_description__c\": [\"How to deal with a situation when you cannot create a new source in Coveo Cloud V2\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka1320000000G8HAAU\"], \"kav_articlenumber__stripped\": [\"2360\"], \"sfversionnumber\": [1], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_validationstatus\": [\"Reviewed\"], \"coveo_foldingparent\": [\"f876b80bd6bf37b498d2d72950bb60471fa79e87fb5ae910942b5d58a48b\"], \"collection\": [\"default\"], \"sfsourceid\": [\"5003200001CoUozAAF\"], \"date\": [1509619413], \"kav_lastmodifiedby.id\": [\"00560000002MKBSAA4\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000002MKBSAA4\"], \"kav_lastmodifiedby.name\": [\"Karel Mpungi\"], \"kav_articlenumber\": [\"000002360\"], \"permanentid\": [\"51badda0dd95d4f821d3412e417799222f19d804a9859e9dd125bd0298a0\"]}",
      "sflastmodifiedbyid" : "00560000002MKBSAA4",
      "syssfownerid" : "00560000002MKBSAA4",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Unable to create a new source in Coveo Cloud V2",
      "rowid" : 5492877,
      "syssfcreatedbyid" : "00560000002MKBSAA4",
      "sfdescriptionc" : "How to deal with a situation when you cannot create a new source in Coveo Cloud V2",
      "size" : 3823,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1498160319000,
      "sfsourceid" : "5003200001CoUozAAF",
      "clickableuri" : "https://na61.salesforce.com/kA1320000000877",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00560000002MKBSAA4",
      "orderingid" : 212384990660371682,
      "sfpublishstatus" : "Online",
      "syssize" : 3823,
      "sysdate" : 1509619413000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Unable to create a new source in Coveo Cloud V2\" uri=\"https://na61.salesforce.com/kA1320000000877\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "USD",
      "sfkbid" : "kA1320000000877CAA",
      "sfcausec" : "When creating a new source in Coveo Cloud V2, you might get the following error:<br><br><img alt=\"User-added image\" height=\"285\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka1320000000G8H&amp;feoid=00N32000002zy1O&amp;refid=0EM32000000Ai3O\" width=\"500\"></img><br><br>In Google Developers tool, you might see this error:\n<pre class=\"ckeditor_codeblock\">\n&quot;message: &quot;Security provider with id &#39;MICROSOFT_DYNAMICS-[IDNUMBER]-[ORG ID]&#39; does not exist. &quot;\n&quot;errorCode: &quot;INVALID_SOURCE_CONFIGURATION&quot;</pre>\n<br>This is simply because the number of security provider limit was reached on this org.By default, this number is 15.",
      "sfdcexpandedproduct" : "All;All|Cloud Platform",
      "syssfcreateddate" : 1498160319000,
      "sflastmodifieddate" : 1499107964000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Karel Mpungi",
      "collection" : "default",
      "sfdcproduct" : [ "Cloud Platform" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187571000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Karel Mpungi",
      "sysclickableuri" : "https://na61.salesforce.com/kA1320000000877",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1499107964000,
      "sfownername" : "Karel Mpungi",
      "sitename" : "Community",
      "sysrowid" : 5492877,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Unable to create a new source in Coveo Cloud V2",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA1320000000877",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000877CAA/language:en_US",
    "Excerpt" : "Environment ... Cause ... When creating a new source in Coveo Cloud V2, you might get the following error: ... In Google Developers tool, you might see this error: \"message: \"Security provider with...",
    "FirstSentences" : null
  }