{
    "title" : "Source failed to start status after back-up",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA1320000000827",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
    "excerpt" : "In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward. ... You will see the source in an error looking like this : ... Environment",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1251,
    "percentScore" : 79.58755,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Source failed to start status after back-up",
      "sfsummary" : "In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward.",
      "sysurihash" : "T2YcxzeeKIpMYDðF",
      "urihash" : "T2YcxzeeKIpMYDðF",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Source failed to start status after back-up\" uri=\"https://na61.salesforce.com/kA1320000000827\" /></parents>",
      "sfdcarticletype" : "Product Issue",
      "sfresolutionc" : "Open a support ticket, support shall verify if it is indeed the same error and inform you once the source is restarted.",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
      "sflastpublisheddate" : 1494870725000,
      "systransactionid" : 161139,
      "sfurlname" : "2306",
      "sfsystemmodstamp" : 1509533085000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Cloud Platform V1",
      "sysconcepts" : "back-up workflow ; Coveo org ; correctly afterward ; done ; Check ; hiccups ; Cause ; Environment",
      "sfkbversionnumber" : "1",
      "concepts" : "back-up workflow ; Coveo org ; correctly afterward ; done ; Check ; hiccups ; Cause ; Environment",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka1320000000FlhAAE",
      "sysindexeddate" : 1518187561000,
      "sfknowledgearticleid" : "kA1320000000827CAA",
      "sfcreatedbyid" : "00532000004voF1AAI",
      "sfconnectorc" : "N/A",
      "permanentid" : "050dd12e0c7d0952aed7942cc7dcc896c31d6c707702f03a84892e61d153",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "Source failed to start status after back-up",
      "sfversionnumber" : 1,
      "sfarticlenumber" : "000002306",
      "date" : 1509533085000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA1320000000827\"], \"sflastmodifiedbyname\": [\"Bruno-Pascal Roy-Dumas\"], \"kav_coveo_version__c__html_stripped\": [\"Cloud Platform V1\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Cloud Platform\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000004voF1AAI\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00532000004voF1AAI\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Source failed to start status after back-up\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000004voF1AAI\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Source failed to start status after back-up\\\" uri=\\\"https://na61.salesforce.com/kA1320000000827\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Source failed to start status after back-up\"], \"kav_isvisibleincsp\": [true], \"sfcreateddate\": [1494869279], \"hashtmlversion\": [true], \"kav_versionnumber\": [1], \"sfcreatedbyname\": [\"Bruno-Pascal Roy-Dumas\"], \"sflastpublisheddate\": [1494870725], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"the back-up workflow might have some hiccups from time to time. Check if a back-up of your Coveo org was done recently.\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1494870725], \"sfsystemmodstamp\": [1509533085], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Cloud Platform\"], \"kav_resolution__c__html_stripped\": [\"Open a support ticket, support shall verify if it is indeed the same error and inform you once the source is restarted.\"], \"clickableuri\": [\"https://na61.salesforce.com/kA1320000000827\"], \"sftitle\": [\"Source failed to start status after back-up\"], \"kav_owner.id\": [\"00532000004voF1AAI\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA1320000000827CAA\"], \"sfdcarticletype\": [\"Product Issue\"], \"kav_cause__c\": [\"the back-up workflow might have some hiccups from time to time. Check if a back-up of your Coveo org was done recently.\"], \"sfislatestversion\": [true], \"sfcausec\": [\"the back-up workflow might have some hiccups from time to time. Check if a back-up of your Coveo org was done recently.\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"2306\"], \"ka_id\": [\"kA1320000000827CAA\"], \"kav_datacategoryselections.datacategoryname\": [\"Cloud_Platform;Product_Issue\"], \"coveo_url\": [\"https://na61.salesforce.com/kA1320000000827\"], \"kav_urlname\": [\"2306\"], \"kav_dc_expanded_product\": [\"All;All|Cloud Platform\"], \"foldingcollection\": [\"3d67bdcabf8dc1d3dbd2348781e5acd7eba432a97178c221177a1d8a20e2\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> <p>In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward. You will see the source in an error looking like this :\\u00a0</p>\\n\\n<p><img alt=\\\"Failed to start error in the admin UI\\\" height=\\\"13\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka1320000000Flh&amp;feoid=00N32000002zy14&amp;refid=0EM32000000Agpe\\\" width=\\\"500\\\"></img></p></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1494870725</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> the back-up workflow might have some hiccups from time to time. Check if a back-up of your Coveo org was done recently.</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> Open a support ticket, support shall verify if it is indeed the same error and inform you once the source is restarted.</div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00532000004voF1AAI\"], \"kav_description__c__html_stripped\": [\"In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward. You will see the source in an error looking like this :\\u00a0\\n \\n\\n \\n\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA1320000000827CAA\"], \"sfknowledgearticleid\": [\"kA1320000000827CAA\"], \"sfownername\": [\"Bruno-Pascal Roy-Dumas\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1494869279], \"language\": [\"English\"], \"coveo_foldingchild\": [\"b8a5366da6644ef0123861dd4e626b98f7bf2633be95cf61b4a8f8ff7f7c\"], \"sfownerid\": [\"00532000004voF1AAI\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1509533085], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Bruno-Pascal Roy-Dumas\"], \"sfcoveoversionc\": [\"Cloud Platform V1\"], \"sfdcexpandedarticletype\": [\"All;All|Product Issue\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"CAD\"], \"sfisdeleted\": [false], \"extractedsize\": [1134], \"size\": [3530], \"kav_summary\": [\"In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward.\"], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"<p>In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward. You will see the source in an error looking like this :\\u00a0</p>\\n\\n<p><img alt=\\\"Failed to start error in the admin UI\\\" height=\\\"13\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka1320000000Flh&amp;feoid=00N32000002zy14&amp;refid=0EM32000000Agpe\\\" width=\\\"500\\\"></img></p>\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1494870725], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka1320000000FlhAAE\"], \"kav_currencyisocode\": [\"CAD\"], \"foldingparent\": [\"b8a5366da6644ef0123861dd4e626b98f7bf2633be95cf61b4a8f8ff7f7c\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"5003200001CK8UHAA1\"], \"sfkbversionnumber\": [1], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"Open a support ticket, support shall verify if it is indeed the same error and inform you once the source is restarted.\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o320000004awGAAQ;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o320000004awHAAQ\"], \"kav_id\": [\"ka1320000000FlhAAE\"], \"sfresolutionc\": [\"Open a support ticket, support shall verify if it is indeed the same error and inform you once the source is restarted.\"], \"foldingchild\": [\"b8a5366da6644ef0123861dd4e626b98f7bf2633be95cf61b4a8f8ff7f7c\"], \"sfsummary\": [\"In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward.\"], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1509533085], \"kav_summary__html_stripped\": [\"In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward.\"], \"kav_dc_article_type\": [\"Product Issue\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Cloud Platform\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Product Issue\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2\"], \"concepts\": [\"back-up workflow ; Coveo org ; correctly afterward ; done ; Check ; hiccups ; Cause ; Environment\"], \"sfkbid\": [\"kA1320000000827CAA\"], \"kav_firstpublisheddate\": [1494870725], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"3d67bdcabf8dc1d3dbd2348781e5acd7eba432a97178c221177a1d8a20e2\"], \"sffirstpublisheddate\": [1494870725], \"sflastmodifieddate\": [1494870725], \"kav_coveo_version__c\": [\"Cloud Platform V1\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00532000004voF1AAI\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Bruno-Pascal Roy-Dumas\"], \"sfarticlenumber\": [\"000002306\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o320000004awGAAQ;02o320000004awHAAQ\"], \"kav_description__c\": [\"<p>In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward. You will see the source in an error looking like this :\\u00a0</p>\\n\\n<p><img alt=\\\"Failed to start error in the admin UI\\\" height=\\\"13\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka1320000000Flh&amp;feoid=00N32000002zy14&amp;refid=0EM32000000Agpe\\\" width=\\\"500\\\"></img></p>\"], \"kav_validationstatus\": [\"Reviewed\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka1320000000FlhAAE\"], \"kav_articlenumber__stripped\": [\"2306\"], \"sfversionnumber\": [1], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"coveo_foldingparent\": [\"b8a5366da6644ef0123861dd4e626b98f7bf2633be95cf61b4a8f8ff7f7c\"], \"collection\": [\"default\"], \"sfsourceid\": [\"5003200001CK8UHAA1\"], \"date\": [1509533085], \"kav_lastmodifiedby.id\": [\"00532000004voF1AAI\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00532000004voF1AAI\"], \"kav_lastmodifiedby.name\": [\"Bruno-Pascal Roy-Dumas\"], \"kav_articlenumber\": [\"000002306\"], \"permanentid\": [\"050dd12e0c7d0952aed7942cc7dcc896c31d6c707702f03a84892e61d153\"]}",
      "sflastmodifiedbyid" : "00532000004voF1AAI",
      "syssfownerid" : "00532000004voF1AAI",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Source failed to start status after back-up",
      "rowid" : 5492732,
      "syssfcreatedbyid" : "00532000004voF1AAI",
      "sfdescriptionc" : "<p>In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward. You will see the source in an error looking like this : </p>\n\n<p><img alt=\"Failed to start error in the admin UI\" height=\"13\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka1320000000Flh&amp;feoid=00N32000002zy14&amp;refid=0EM32000000Agpe\" width=\"500\"></img></p>",
      "size" : 3530,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1494869279000,
      "sfsourceid" : "5003200001CK8UHAA1",
      "clickableuri" : "https://na61.salesforce.com/kA1320000000827",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00532000004voF1AAI",
      "orderingid" : 212384990660371540,
      "sfpublishstatus" : "Online",
      "syssize" : 3530,
      "sysdate" : 1509533085000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Source failed to start status after back-up\" uri=\"https://na61.salesforce.com/kA1320000000827\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Product Issue",
      "sfcurrencyisocode" : "CAD",
      "sfkbid" : "kA1320000000827CAA",
      "sfcausec" : "the back-up workflow might have some hiccups from time to time. Check if a back-up of your Coveo org was done recently.",
      "sfdcexpandedproduct" : "All;All|Cloud Platform",
      "syssfcreateddate" : 1494869279000,
      "sflastmodifieddate" : 1494870725000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Bruno-Pascal Roy-Dumas",
      "collection" : "default",
      "sfdcproduct" : [ "Cloud Platform" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187561000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Bruno-Pascal Roy-Dumas",
      "sysclickableuri" : "https://na61.salesforce.com/kA1320000000827",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1494870725000,
      "sfownername" : "Bruno-Pascal Roy-Dumas",
      "sitename" : "Community",
      "sysrowid" : 5492732,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Source failed to start status after back-up",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA1320000000827",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA1320000000827CAA/language:en_US",
    "Excerpt" : "In the back-up workflow the sources are all stopped and it might happen that a source does not start correctly afterward. ... You will see the source in an error looking like this : ... Environment",
    "FirstSentences" : null
  }