{
    "title" : "Knowledge source unable to authenticate issue persists after re-authentication",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA10d0000004MZN",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
    "excerpt" : "SALESFORCE_UNABLE_TO_AUTHENTICATE causing sources are unable update on knowledge source despite re-authenticating as per https://support.coveo.com/s/article/1970 ... crawling account does not the r...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1341,
    "percentScore" : 82.40069,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Knowledge source unable to authenticate issue persists after re-authentication",
      "sfsummary" : "Knowledge source unable to authenticate issue persists after re-authentication",
      "sysurihash" : "DNtpð83L0FJymbVI",
      "urihash" : "DNtpð83L0FJymbVI",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Knowledge source unable to authenticate issue persists after re-authentication\" uri=\"https://na61.salesforce.com/kA10d0000004MZN\" /></parents>",
      "sfdcarticletype" : "Problem/Fix",
      "sfresolutionc" : "in user profile &gt;&gt; App Permissions &gt;&gt; Knowledge Management &gt; enabled all permissions for Knowledge Management<br><br><img alt=\"User-added image\" height=\"107\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Svn&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000020Q2\" width=\"500\"></img>",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
      "sflastpublisheddate" : 1509394008000,
      "systransactionid" : 161139,
      "sfurlname" : "2742",
      "sfsystemmodstamp" : 1516275942000,
      "sfisvisibleinapp" : "true",
      "sfkbversionnumber" : "1",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka10d0000004SvnAAE",
      "sysindexeddate" : 1518187596000,
      "sfknowledgearticleid" : "kA10d0000004MZNCA2",
      "sfcreatedbyid" : "00560000002ljDtAAI",
      "sfconnectorc" : "N/A",
      "permanentid" : "6246de7b9c5ad5db3d06fb459888496e47008e944f977ea72640a0b82e2e",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "Knowledge source unable to authenticate issue persists after re-authentication",
      "sfversionnumber" : 1,
      "sfarticlenumber" : "000002742",
      "date" : 1516275942000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA10d0000004MZN\"], \"sflastmodifiedbyname\": [\"Jonathan Garneau\"], \"kav_coveo_version__c__html_stripped\": [\"\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Cloud Platform\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002ljDtAAI\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00560000002ljDtAAI\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Knowledge source unable to authenticate issue persists after re-authentication\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002ljDtAAI\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Knowledge source unable to authenticate issue persists after re-authentication\\\" uri=\\\"https://na61.salesforce.com/kA10d0000004MZN\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Knowledge source unable to authenticate issue persists after re-authentication\"], \"kav_isvisibleincsp\": [true], \"sfcreateddate\": [1509393615], \"hashtmlversion\": [true], \"kav_versionnumber\": [1], \"sfcreatedbyname\": [\"Jonathan Garneau\"], \"sflastpublisheddate\": [1509394008], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"crawling account does not the right Knowledge Management permissions \\n \\n \"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1509394008], \"sfsystemmodstamp\": [1516275942], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Cloud Platform\"], \"clickableuri\": [\"https://na61.salesforce.com/kA10d0000004MZN\"], \"sftitle\": [\"Knowledge source unable to authenticate issue persists after re-authentication\"], \"kav_owner.id\": [\"00560000002ljDtAAI\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA10d0000004MZNCA2\"], \"sfdcarticletype\": [\"Problem/Fix\"], \"kav_cause__c\": [\"crawling account does not the right Knowledge Management permissions<br><br><img alt=\\\"User-added image\\\" height=\\\"105\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Svn&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000020Px\\\" width=\\\"500\\\"></img>\"], \"sfislatestversion\": [true], \"sfcausec\": [\"crawling account does not the right Knowledge Management permissions<br><br><img alt=\\\"User-added image\\\" height=\\\"105\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Svn&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000020Px\\\" width=\\\"500\\\"></img>\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"2742\"], \"ka_id\": [\"kA10d0000004MZNCA2\"], \"kav_datacategoryselections.datacategoryname\": [\"Cloud_Platform;Configuration\"], \"coveo_url\": [\"https://na61.salesforce.com/kA10d0000004MZN\"], \"kav_urlname\": [\"2742\"], \"kav_dc_expanded_product\": [\"All;All|Cloud Platform\"], \"foldingcollection\": [\"f149e72d6190b6a0875436369f09fe50a5a723e77b69f383fce5a2db1556\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> SALESFORCE_UNABLE_TO_AUTHENTICATE causing sources are unable update on knowledge source despite re-authenticating as per\\u00a0https://support.coveo.com/s/article/1970</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1509394008</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> crawling account does not the right Knowledge Management permissions<br><br><img alt=\\\"User-added image\\\" height=\\\"105\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Svn&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000020Px\\\" width=\\\"500\\\"></img></div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> in user profile &gt;&gt; App Permissions &gt;&gt; Knowledge Management &gt; enabled all permissions for Knowledge Management<br><br><img alt=\\\"User-added image\\\" height=\\\"107\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Svn&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000020Q2\\\" width=\\\"500\\\"></img></div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00560000002ljDtAAI\"], \"kav_description__c__html_stripped\": [\"SALESFORCE_UNABLE_TO_AUTHENTICATE causing sources are unable update on knowledge source despite re-authenticating as per\\u00a0https://support.coveo.com/s/article/1970\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA10d0000004MZNCA2\"], \"sfknowledgearticleid\": [\"kA10d0000004MZNCA2\"], \"sfownername\": [\"Jonathan Garneau\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1509393615], \"language\": [\"English\"], \"coveo_foldingchild\": [\"b7995c6acbcb742ab6a5c4a34f9fb1d0f63d45d3500d0a28d133f8811013\"], \"sfownerid\": [\"00560000002ljDtAAI\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1516275942], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Jonathan Garneau\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"USD\"], \"sfisdeleted\": [false], \"extractedsize\": [978], \"size\": [3527], \"kav_summary\": [\"Knowledge source unable to authenticate issue persists after re-authentication\"], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"SALESFORCE_UNABLE_TO_AUTHENTICATE causing sources are unable update on knowledge source despite re-authenticating as per\\u00a0https://support.coveo.com/s/article/1970\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1509394008], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka10d0000004SvnAAE\"], \"kav_currencyisocode\": [\"USD\"], \"foldingparent\": [\"b7995c6acbcb742ab6a5c4a34f9fb1d0f63d45d3500d0a28d133f8811013\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"5000d00001FqX9uAAF\"], \"sfkbversionnumber\": [1], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"in user profile &gt;&gt; App Permissions &gt;&gt; Knowledge Management &gt; enabled all permissions for Knowledge Management<br><br><img alt=\\\"User-added image\\\" height=\\\"107\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Svn&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000020Q2\\\" width=\\\"500\\\"></img>\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m5Q9AAI;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m5Q8AAI\"], \"kav_id\": [\"ka10d0000004SvnAAE\"], \"sfresolutionc\": [\"in user profile &gt;&gt; App Permissions &gt;&gt; Knowledge Management &gt; enabled all permissions for Knowledge Management<br><br><img alt=\\\"User-added image\\\" height=\\\"107\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Svn&amp;feoid=00N32000002zy1J&amp;refid=0EM0d00000020Q2\\\" width=\\\"500\\\"></img>\"], \"foldingchild\": [\"b7995c6acbcb742ab6a5c4a34f9fb1d0f63d45d3500d0a28d133f8811013\"], \"sfsummary\": [\"Knowledge source unable to authenticate issue persists after re-authentication\"], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1516275942], \"kav_summary__html_stripped\": [\"Knowledge source unable to authenticate issue persists after re-authentication\"], \"kav_dc_article_type\": [\"Problem/Fix\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Cloud Platform\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2\"], \"sfkbid\": [\"kA10d0000004MZNCA2\"], \"kav_firstpublisheddate\": [1509394008], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"f149e72d6190b6a0875436369f09fe50a5a723e77b69f383fce5a2db1556\"], \"sffirstpublisheddate\": [1509394008], \"sflastmodifieddate\": [1509394008], \"kav_resolution__c__html_stripped\": [\"in user profile >> App Permissions >> Knowledge Management > enabled all permissions for Knowledge Management \\n \\n \"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002ljDtAAI\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Jonathan Garneau\"], \"sfarticlenumber\": [\"000002742\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o0d000000m5Q9AAI;02o0d000000m5Q8AAI\"], \"kav_description__c\": [\"SALESFORCE_UNABLE_TO_AUTHENTICATE causing sources are unable update on knowledge source despite re-authenticating as per\\u00a0https://support.coveo.com/s/article/1970\"], \"kav_validationstatus\": [\"Needs Review\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka10d0000004SvnAAE\"], \"kav_articlenumber__stripped\": [\"2742\"], \"sfversionnumber\": [1], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"coveo_foldingparent\": [\"b7995c6acbcb742ab6a5c4a34f9fb1d0f63d45d3500d0a28d133f8811013\"], \"collection\": [\"default\"], \"sfsourceid\": [\"5000d00001FqX9uAAF\"], \"date\": [1516275942], \"kav_lastmodifiedby.id\": [\"00560000002ljDtAAI\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Needs Review\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000002ljDtAAI\"], \"kav_lastmodifiedby.name\": [\"Jonathan Garneau\"], \"kav_articlenumber\": [\"000002742\"], \"permanentid\": [\"6246de7b9c5ad5db3d06fb459888496e47008e944f977ea72640a0b82e2e\"]}",
      "sflastmodifiedbyid" : "00560000002ljDtAAI",
      "syssfownerid" : "00560000002ljDtAAI",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Knowledge source unable to authenticate issue persists after re-authentication",
      "rowid" : 5493278,
      "syssfcreatedbyid" : "00560000002ljDtAAI",
      "sfdescriptionc" : "SALESFORCE_UNABLE_TO_AUTHENTICATE causing sources are unable update on knowledge source despite re-authenticating as per https://support.coveo.com/s/article/1970",
      "size" : 3527,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1509393615000,
      "sfsourceid" : "5000d00001FqX9uAAF",
      "clickableuri" : "https://na61.salesforce.com/kA10d0000004MZN",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00560000002ljDtAAI",
      "orderingid" : 212384990660372084,
      "sfpublishstatus" : "Online",
      "syssize" : 3527,
      "sysdate" : 1516275942000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Knowledge source unable to authenticate issue persists after re-authentication\" uri=\"https://na61.salesforce.com/kA10d0000004MZN\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix",
      "sfcurrencyisocode" : "USD",
      "sfkbid" : "kA10d0000004MZNCA2",
      "sfcausec" : "crawling account does not the right Knowledge Management permissions<br><br><img alt=\"User-added image\" height=\"105\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004Svn&amp;feoid=00N32000002zy1O&amp;refid=0EM0d00000020Px\" width=\"500\"></img>",
      "sfdcexpandedproduct" : "All;All|Cloud Platform",
      "syssfcreateddate" : 1509393615000,
      "sflastmodifieddate" : 1509394008000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Needs Review",
      "sflastmodifiedbyname" : "Jonathan Garneau",
      "collection" : "default",
      "sfdcproduct" : [ "Cloud Platform" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187596000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Jonathan Garneau",
      "sysclickableuri" : "https://na61.salesforce.com/kA10d0000004MZN",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1509394008000,
      "sfownername" : "Jonathan Garneau",
      "sitename" : "Community",
      "sysrowid" : 5493278,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Knowledge source unable to authenticate issue persists after re-authentication",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA10d0000004MZN",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MZNCA2/language:en_US",
    "Excerpt" : "SALESFORCE_UNABLE_TO_AUTHENTICATE causing sources are unable update on knowledge source despite re-authenticating as per https://support.coveo.com/s/article/1970 ... crawling account does not the r...",
    "FirstSentences" : null
  }