{
    "title" : "Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE",
    "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
    "printableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
    "clickUri" : "https://na61.salesforce.com/kA10d0000004Mau",
    "uniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
    "excerpt" : "When indexing a source, if you are seeing warning like the following one in the \"Log Browser\" of the Cloud Platform : ... This error can happen if you have deleted a source and re-created it using ...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1277,
    "percentScore" : 80.41034,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE",
      "sysurihash" : "TlðpptXdrqBLNrC5",
      "urihash" : "TlðpptXdrqBLNrC5",
      "parents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE\" uri=\"https://na61.salesforce.com/kA10d0000004Mau\" /></parents>",
      "sfdcarticletype" : "Problem/Fix;Product Issue",
      "sfresolutionc" : "A fix will be included in the Cloud Platform to make the source name case sensitive, this will prevent something like this to happen in the future. For the moment (November 3rd 2017), in order to fix this, you&#39;ll need to create new sources with a different name and delete the existing one. ",
      "sysuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
      "sysprintableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
      "sflastpublisheddate" : 1512589102000,
      "systransactionid" : 161139,
      "sfurlname" : "2752",
      "sfsystemmodstamp" : 1512647129000,
      "sfisvisibleinapp" : "true",
      "sfcoveoversionc" : "Cloud Platform",
      "sysconcepts" : "Cloud Platform ; Youtube ; request ; deleted multiple ; Log Browser ; seeing warning ; existing ; fix ; interactions ; Resolution ; Environment",
      "sfkbversionnumber" : "1",
      "concepts" : "Cloud Platform ; Youtube ; request ; deleted multiple ; Log Browser ; seeing warning ; existing ; fix ; interactions ; Resolution ; Environment",
      "printableuri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
      "documenttype" : "article",
      "sfkbarticlekavid" : "ka10d0000004T09AAE",
      "sysindexeddate" : 1518187593000,
      "sfknowledgearticleid" : "kA10d0000004MauCAE",
      "sfcreatedbyid" : "00560000000miRvAAI",
      "sfconnectorc" : "N/A",
      "permanentid" : "b5b51709d34bc2ee07d5a941dc16e6cc098df2eeb48f9a3bd5e7405d32e3",
      "syslanguage" : [ "English" ],
      "transactionid" : 161139,
      "sfisvisibleinprm" : "true",
      "title" : "Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE",
      "sfversionnumber" : 1,
      "sfarticlenumber" : "000002752",
      "date" : 1512647129000,
      "objecttype" : "KB Article",
      "allmetadatavalues" : "{\"kav_lastmodifiedby.attribute.type\": [\"User\"], \"coveo_short_id\": [\"kA10d0000004Mau\"], \"sflastmodifiedbyname\": [\"Karel Mpungi\"], \"kav_coveo_version__c__html_stripped\": [\"Cloud Platform\"], \"fileextension\": [\"\"], \"sfdcexpandedproduct\": [\"All;All|Cloud Platform\"], \"kav_createdby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000000miRvAAI\"], \"sflanguage\": [\"en_US\"], \"kav_createdby.attribute.type\": [\"User\"], \"kav_createdby.id\": [\"00560000000miRvAAI\"], \"kav_language\": [\"en_US\"], \"sfsitecoreversionc\": [\"N/A\"], \"sourcetype\": [\"Salesforce\"], \"title\": [\"Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE\"], \"source\": [\"Salesforce Public Items\"], \"kav_owner.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000000miRvAAI\"], \"parents\": [\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><parents><parent name=\\\"Organization\\\" uri=\\\"https://na61.salesforce.com/home/home.jsp\\\" /><parent name=\\\"KB_Article__ka\\\" uri=\\\"http://www.salesforce.com/org:organization/articletype:KB_Article\\\" /><parent name=\\\"Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE\\\" uri=\\\"https://na61.salesforce.com/kA10d0000004Mau\\\" /></parents>\"], \"sfisvisibleinprm\": [true], \"kav_title\": [\"Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE\"], \"kav_isvisibleincsp\": [true], \"hashtmlversion\": [true], \"kav_versionnumber\": [1], \"sfcreatedbyname\": [\"Steve Mercier\"], \"sflastpublisheddate\": [1512589102], \"objecttypelabel\": [\"KB Article\"], \"kav_cause__c__html_stripped\": [\"This is a platform (source service) issue. What happened is that you might have created/deleted multiple sources with the same name, but with different casing (\\\"YouTube\\\" vs \\\"Youtube\\\" for example). \\n \\n The source name in the index is case insensitive, so you do some interactions where your deletes of the previous sources happened after the creation of your new ones. The new added source could be ignored (the old one still exist) and the deletes request will delete all sources. The end result is that the sources are gone from the index.\"], \"originalhtmlcharset\": [1200], \"coveo_connector_hasbinarydata\": [false], \"kav_lastpublisheddate\": [1512589102], \"sfsystemmodstamp\": [1512647129], \"ka_attribute.type\": [\"KB_Article__ka\"], \"sfdcproduct\": [\"Cloud Platform\"], \"kav_resolution__c__html_stripped\": [\"A fix will be included in the Cloud Platform to make the source name case sensitive, this will prevent something like this to happen in the future. For the moment (November 3rd 2017), in order to fix this, you'll need to create new sources with a different name and delete the existing one.\\u00a0\"], \"clickableuri\": [\"https://na61.salesforce.com/kA10d0000004Mau\"], \"sftitle\": [\"Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE\"], \"kav_owner.id\": [\"00560000000miRvAAI\"], \"sfisvisibleinapp\": [true], \"ka_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__ka/kA10d0000004MauCAE\"], \"sfdcarticletype\": [\"Problem/Fix;Product Issue\"], \"kav_cause__c\": [\"This is a platform (source service) issue. What happened is that you might have created/deleted multiple sources with the same name, but with different casing (&quot;YouTube&quot; vs &quot;Youtube&quot; for example).<br><br>The source name in the index is case insensitive, so you do some interactions where your deletes of the previous sources happened after the creation of your new ones. The new added source could be ignored (the old one still exist) and the deletes request will delete all sources. The end result is that the sources are gone from the index.\"], \"sfislatestversion\": [true], \"sfcausec\": [\"This is a platform (source service) issue. What happened is that you might have created/deleted multiple sources with the same name, but with different casing (&quot;YouTube&quot; vs &quot;Youtube&quot; for example).<br><br>The source name in the index is case insensitive, so you do some interactions where your deletes of the previous sources happened after the creation of your new ones. The new added source could be ignored (the old one still exist) and the deletes request will delete all sources. The end result is that the sources are gone from the index.\"], \"contenttype\": [\"binarydata\"], \"sfurlname\": [\"2752\"], \"ka_id\": [\"kA10d0000004MauCAE\"], \"kav_datacategoryselections.datacategoryname\": [\"Cloud_Platform;Product_Issue;Configuration\"], \"coveo_url\": [\"https://na61.salesforce.com/kA10d0000004Mau\"], \"kav_urlname\": [\"2752\"], \"kav_dc_expanded_product\": [\"All;All|Cloud Platform\"], \"foldingcollection\": [\"fc77dcef9e7ea35da2605347d95bdc6d69e1235c9f1723476f15793e39af\"], \"body\": [\"<html>   <body>     <div style=\\\"background-color: #fff;border: 2px solid #BBC5CC;border-radius: 4px;float: left;font-family: lato;margin-left: 15px;margin-right: 15px;margin-bottom: 4%;padding: 10px;width: 60%;\\\">       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Description         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> When indexing a source, if you are seeing warning like the following one in the &quot;Log Browser&quot; of the Cloud Platform :<br><br><img alt=\\\"User-added image\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004T09&amp;feoid=00N32000002zy14&amp;refid=0EM0d00000020be\\\"></img><br><br>This error can happen if you have deleted a source and re-created it using the same name without allowing enough time for the Platform to complete the delete request.</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Environment         </div>       </div>       <br/>       <table>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Product</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Sitecore Version</td>           <td>N/A</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Connector</td>           <td>N/A</td>         </tr>         <tr>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Published</td>           <td>1512589102</td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Version</td>           <td></td>           <td style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;font-weight: 600;\\\">Build</td>           <td></td>         </tr>       </table>       <br/>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Cause         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> This is a platform (source service) issue. What happened is that you might have created/deleted multiple sources with the same name, but with different casing (&quot;YouTube&quot; vs &quot;Youtube&quot; for example).<br><br>The source name in the index is case insensitive, so you do some interactions where your deletes of the previous sources happened after the creation of your new ones. The new added source could be ignored (the old one still exist) and the deletes request will delete all sources. The end result is that the sources are gone from the index.</div>       <div style=\\\"font-size: 1.5em;font-weight: 600;Padding-top: 30px;border-bottom: 1px solid #BBC5CC;\\\">         <div style=\\\"border-left: 1px solid #BBC5CC;border-top: 1px solid #BBC5CC;color: #296896;padding: 10px;width: 15%;\\\">           Resolution         </div>       </div>       <div style=\\\"margin-left: 35px;margin-top: 10px;font-size: 1em;\\\"> A fix will be included in the Cloud Platform to make the source name case sensitive, this will prevent something like this to happen in the future. For the moment (November 3rd 2017), in order to fix this, you&#39;ll need to create new sources with a different name and delete the existing one.\\u00a0</div>     </div>   </body> </html>\"], \"sfpublishstatus\": [\"Online\"], \"sfcreatedbyid\": [\"00560000000miRvAAI\"], \"kav_description__c__html_stripped\": [\"When indexing a source, if you are seeing warning like the following one in the \\\"Log Browser\\\" of the Cloud Platform : \\n \\n  \\n \\n This error can happen if you have deleted a source and re-created it using the same name without allowing enough time for the Platform to complete the delete request.\"], \"kav_islatestversion\": [true], \"kav_knowledgearticleid\": [\"kA10d0000004MauCAE\"], \"sfknowledgearticleid\": [\"kA10d0000004MauCAE\"], \"sfownername\": [\"Steve Mercier\"], \"kav_datacategoryselections.attribute.type\": [\"KB_Article__DataCategorySelection;KB_Article__DataCategorySelection;KB_Article__DataCategorySelection\"], \"detectedtitle\": [\"Description\"], \"kav_createddate\": [1509710968], \"language\": [\"English\"], \"coveo_foldingchild\": [\"fee8d17a6b6d6ba8b88842aa21f3e17fdfcaf44fb9befd97612079783918\"], \"sfownerid\": [\"00560000000miRvAAI\"], \"kav_createdby.coveo_record_size\": [2], \"kav_systemmodstamp\": [1512647129], \"objecttype\": [\"KB Article\"], \"connectortype\": [\"Salesforce2\"], \"kav_coveo_record_size\": [4], \"originaluri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US\"], \"sfisvisibleincsp\": [true], \"convertertype\": [\"TYPE_HTML\"], \"filetype\": [\"SalesforceItem\"], \"kav_owner.name\": [\"Steve Mercier\"], \"sfcoveoversionc\": [\"Cloud Platform\"], \"sfdcexpandedarticletype\": [\"All;All|Problem/Fix;All|Product Issue\"], \"objecttypelabelplural\": [\"KB Articles\"], \"sfcurrencyisocode\": [\"USD\"], \"sfisdeleted\": [false], \"extractedsize\": [2528], \"size\": [4938], \"kav_publishstatus\": [\"Online\"], \"kav_connector__c\": [\"N/A\"], \"generateexcerpt\": [true], \"sfdescriptionc\": [\"When indexing a source, if you are seeing warning like the following one in the &quot;Log Browser&quot; of the Cloud Platform :<br><br><img alt=\\\"User-added image\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004T09&amp;feoid=00N32000002zy14&amp;refid=0EM0d00000020be\\\"></img><br><br>This error can happen if you have deleted a source and re-created it using the same name without allowing enough time for the Platform to complete the delete request.\"], \"sfarticletype\": [\"KB_Article__kav\"], \"kav_articletype\": [\"KB_Article__kav\"], \"kav_lastmodifieddate\": [1512589102], \"documenttype\": [\"article\"], \"sfkbarticlekavid\": [\"ka10d0000004T09AAE\"], \"kav_currencyisocode\": [\"USD\"], \"foldingparent\": [\"fee8d17a6b6d6ba8b88842aa21f3e17fdfcaf44fb9befd97612079783918\"], \"mappingtype\": [\"KB_Article\"], \"kav_isvisibleinpkb\": [true], \"kav_sourceid\": [\"5000d00001Fs3SVAAZ\"], \"sfkbversionnumber\": [1], \"kav_isvisibleinapp\": [true], \"kav_resolution__c\": [\"A fix will be included in the Cloud Platform to make the source name case sensitive, this will prevent something like this to happen in the future. For the moment (November 3rd 2017), in order to fix this, you&#39;ll need to create new sources with a different name and delete the existing one.\\u00a0\"], \"coveo_objecttype\": [\"KB_Article\"], \"printableuri\": [\"http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US\"], \"kav_datacategoryselections.attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m5nSAAQ;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m5nTAAQ;/services/data/v34.0/sobjects/KB_Article__DataCategorySelection/02o0d000000m5ncAAA\"], \"kav_id\": [\"ka10d0000004T09AAE\"], \"sfresolutionc\": [\"A fix will be included in the Cloud Platform to make the source name case sensitive, this will prevent something like this to happen in the future. For the moment (November 3rd 2017), in order to fix this, you&#39;ll need to create new sources with a different name and delete the existing one.\\u00a0\"], \"foldingchild\": [\"fee8d17a6b6d6ba8b88842aa21f3e17fdfcaf44fb9befd97612079783918\"], \"sfcreateddate\": [1509710968], \"kav_sitecore_version__c\": [\"N/A\"], \"kav_owner.coveo_record_size\": [2], \"kav_coveo_effective_modstamp\": [1512647129], \"kav_summary__html_stripped\": [\"\"], \"kav_dc_article_type\": [\"Problem/Fix;Product Issue\"], \"sfconnectorc\": [\"N/A\"], \"kav_dc_product\": [\"Cloud Platform\"], \"ka_coveo_record_size\": [2], \"kav_dc_expanded_article_type\": [\"All;All|Problem/Fix;All|Product Issue\"], \"kav_datacategoryselections.coveo_record_size\": [\"2;2;2\"], \"concepts\": [\"Cloud Platform ; Youtube ; request ; deleted multiple ; Log Browser ; seeing warning ; existing ; fix ; interactions ; Resolution ; Environment\"], \"sfkbid\": [\"kA10d0000004MauCAE\"], \"kav_firstpublisheddate\": [1512589102], \"coveo_organization_id\": [\"00D3000000007r2\"], \"coveo_foldingcollection\": [\"fc77dcef9e7ea35da2605347d95bdc6d69e1235c9f1723476f15793e39af\"], \"sffirstpublisheddate\": [1512589102], \"sflastmodifieddate\": [1512589102], \"kav_coveo_version__c\": [\"Cloud Platform\"], \"kav_vendor_version__c__html_stripped\": [\"\"], \"detectedlanguage\": [1], \"kav_isvisibleinprm\": [true], \"kav_owner.attribute.type\": [\"Name\"], \"kav_lastmodifiedby.attribute.url\": [\"/services/data/v34.0/sobjects/User/00560000002MKBSAA4\"], \"sitename\": [\"Community\"], \"kav_createdby.name\": [\"Steve Mercier\"], \"sfarticlenumber\": [\"000002752\"], \"kav_lastmodifiedby.coveo_record_size\": [2], \"sfisvisibleinpkb\": [true], \"kav_datacategoryselections.id\": [\"02o0d000000m5nSAAQ;02o0d000000m5nTAAQ;02o0d000000m5ncAAA\"], \"kav_description__c\": [\"When indexing a source, if you are seeing warning like the following one in the &quot;Log Browser&quot; of the Cloud Platform :<br><br><img alt=\\\"User-added image\\\" src=\\\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004T09&amp;feoid=00N32000002zy14&amp;refid=0EM0d00000020be\\\"></img><br><br>This error can happen if you have deleted a source and re-created it using the same name without allowing enough time for the Platform to complete the delete request.\"], \"kav_attribute.url\": [\"/services/data/v34.0/sobjects/KB_Article__kav/ka10d0000004T09AAE\"], \"kav_articlenumber__stripped\": [\"2752\"], \"sfversionnumber\": [1], \"kav_attribute.type\": [\"KB_Article__kav\"], \"kav_validationstatus\": [\"Reviewed\"], \"coveo_foldingparent\": [\"fee8d17a6b6d6ba8b88842aa21f3e17fdfcaf44fb9befd97612079783918\"], \"collection\": [\"default\"], \"sfsourceid\": [\"5000d00001Fs3SVAAZ\"], \"date\": [1512647129], \"kav_lastmodifiedby.id\": [\"00560000002MKBSAA4\"], \"kav_datacategoryselections.datacategorygroupname\": [\"Product;Article_Type;Article_Type\"], \"conversionstate\": [0], \"sfvalidationstatus\": [\"Reviewed\"], \"kav_isdeleted\": [false], \"sflastmodifiedbyid\": [\"00560000002MKBSAA4\"], \"kav_lastmodifiedby.name\": [\"Karel Mpungi\"], \"kav_articlenumber\": [\"000002752\"], \"permanentid\": [\"b5b51709d34bc2ee07d5a941dc16e6cc098df2eeb48f9a3bd5e7405d32e3\"]}",
      "sflastmodifiedbyid" : "00560000002MKBSAA4",
      "syssfownerid" : "00560000000miRvAAI",
      "sfsitecoreversionc" : "N/A",
      "sourcetype" : "Salesforce",
      "sysconnectortype" : "Salesforce2",
      "sftitle" : "Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE",
      "rowid" : 5493225,
      "syssfcreatedbyid" : "00560000000miRvAAI",
      "sfdescriptionc" : "When indexing a source, if you are seeing warning like the following one in the &quot;Log Browser&quot; of the Cloud Platform :<br><br><img alt=\"User-added image\" src=\"https://c.na61.content.force.com/servlet/rtaImage?eid=ka10d0000004T09&amp;feoid=00N32000002zy14&amp;refid=0EM0d00000020be\"></img><br><br>This error can happen if you have deleted a source and re-created it using the same name without allowing enough time for the Platform to complete the delete request.",
      "size" : 4938,
      "sfislatestversion" : "true",
      "sysdocumenttype" : "article",
      "sfcreateddate" : 1509710968000,
      "sfsourceid" : "5000d00001Fs3SVAAZ",
      "clickableuri" : "https://na61.salesforce.com/kA10d0000004Mau",
      "syssource" : "Salesforce Public Items",
      "sfownerid" : "00560000000miRvAAI",
      "orderingid" : 212384990660372035,
      "sfpublishstatus" : "Online",
      "syssize" : 4938,
      "sysdate" : 1512647129000,
      "sflanguage" : "en_US",
      "sysparents" : "<?xml version=\"1.0\" encoding=\"utf-16\"?><parents><parent name=\"Organization\" uri=\"https://na61.salesforce.com/home/home.jsp\" /><parent name=\"KB_Article__ka\" uri=\"http://www.salesforce.com/org:organization/articletype:KB_Article\" /><parent name=\"Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE\" uri=\"https://na61.salesforce.com/kA10d0000004Mau\" /></parents>",
      "sfdcexpandedarticletype" : "All;All|Problem/Fix;All|Product Issue",
      "sfcurrencyisocode" : "USD",
      "sfkbid" : "kA10d0000004MauCAE",
      "sfcausec" : "This is a platform (source service) issue. What happened is that you might have created/deleted multiple sources with the same name, but with different casing (&quot;YouTube&quot; vs &quot;Youtube&quot; for example).<br><br>The source name in the index is case insensitive, so you do some interactions where your deletes of the previous sources happened after the creation of your new ones. The new added source could be ignored (the old one still exist) and the deletes request will delete all sources. The end result is that the sources are gone from the index.",
      "sfdcexpandedproduct" : "All;All|Cloud Platform",
      "syssfcreateddate" : 1509710968000,
      "sflastmodifieddate" : 1512589102000,
      "sfisvisibleinpkb" : "true",
      "source" : "Salesforce Public Items",
      "sfisdeleted" : "false",
      "sfisvisibleincsp" : "true",
      "sfvalidationstatus" : "Reviewed",
      "sflastmodifiedbyname" : "Karel Mpungi",
      "collection" : "default",
      "sfdcproduct" : [ "Cloud Platform" ],
      "syssourcetype" : "Salesforce",
      "sfarticletype" : "KB_Article__kav",
      "indexeddate" : 1518187593000,
      "connectortype" : "Salesforce2",
      "filetype" : "SalesforceItem",
      "sfcreatedbyname" : "Steve Mercier",
      "sysclickableuri" : "https://na61.salesforce.com/kA10d0000004Mau",
      "sysfiletype" : "SalesforceItem",
      "language" : [ "English" ],
      "sffirstpublisheddate" : 1512589102000,
      "sfownername" : "Steve Mercier",
      "sitename" : "Community",
      "sysrowid" : 5493225,
      "uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
      "syscollection" : "default"
    },
    "Title" : "Content is not being indexed due to indexing stage error: UNSUPPORTED_SOURCE",
    "Uri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
    "PrintableUri" : "http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
    "ClickUri" : "https://na61.salesforce.com/kA10d0000004Mau",
    "UniqueId" : "42.13819$http://www.salesforce.com/org:organization/articletype:KB_Article/article:kA10d0000004MauCAE/language:en_US",
    "Excerpt" : "When indexing a source, if you are seeing warning like the following one in the \"Log Browser\" of the Cloud Platform : ... This error can happen if you have deleted a source and re-created it using ...",
    "FirstSentences" : null
  }