{
    "title" : "401 - You must provide credentials to perform this operation - NoAuthenticationException (Coveo for Salesforce)",
    "uri" : "https://developers.coveo.com/display/SupportKB/Page/3080921/24641753/36644285",
    "printableUri" : "https://developers.coveo.com/display/SupportKB/Page/3080921/24641753/36644285",
    "clickUri" : "https://developers.coveo.com/pages/viewpage.action?pageId=36644285",
    "uniqueId" : "42.58196$https://developers.coveo.com/display/SupportKB/Page/3080921/24641753/36644285",
    "excerpt" : "This is the simplest cause. ... We've seen occurrences where the link between the Coveo for Salesforce package on the customer Salesforce instance, and the Coveo org, have correctly been created by...",
    "firstSentences" : null,
    "summary" : null,
    "flags" : "HasHtmlVersion",
    "hasHtmlVersion" : true,
    "hasMobileHtmlVersion" : false,
    "score" : 1296,
    "percentScore" : 81.00633,
    "rankingInfo" : null,
    "rating" : 3.0,
    "isTopResult" : false,
    "isRecommendation" : false,
    "titleHighlights" : [ ],
    "firstSentencesHighlights" : [ ],
    "excerptHighlights" : [ ],
    "printableUriHighlights" : [ ],
    "summaryHighlights" : [ ],
    "parentResult" : null,
    "childResults" : [ ],
    "totalNumberOfChildResults" : 0,
    "raw" : {
      "systitle" : "401 - You must provide credentials to perform this operation - NoAuthenticationException (Coveo for Salesforce)",
      "cfspacekey" : "SupportKB",
      "sysauthor" : "Alexandre Moreau",
      "sysurihash" : "bJM2ei6B0fOxzSBV",
      "urihash" : "bJM2ei6B0fOxzSBV",
      "parents" : "<parents><parent name=\"Coveo Support Knowledge Base\" uri=\"https://developers.coveo.com/display/SupportKB\" /><parent name=\"Coveo Support KB\" uri=\"https://developers.coveo.com/display/SupportKB/Coveo+Support+KB\" /><parent name=\"Coveo for Salesforce - Support KB\" uri=\"https://developers.coveo.com/display/SupportKB/Coveo+for+Salesforce+-+Support+KB\" /></parents>",
      "sysuri" : "https://developers.coveo.com/display/SupportKB/Page/3080921/24641753/36644285",
      "systransactionid" : 149713,
      "sysconcepts" : "Coveo org ; Salesforce V2 ; sufficient permissions ; Installed Packages ; admin ; cloud ; renewal task ; re-linking ; environment ; limitations inherent ; exact failure ; confident the fix ; access the Provisioning ; cloudplatform ; incovenience",
      "concepts" : "Coveo org ; Salesforce V2 ; sufficient permissions ; Installed Packages ; admin ; cloud ; renewal task ; re-linking ; environment ; limitations inherent ; exact failure ; confident the fix ; access the Provisioning ; cloudplatform ; incovenience",
      "sysindexeddate" : 1513890271000,
      "permanentid" : "4a8c66b88d583710f0f6b149b032a4ccef2c4443083170fb580dc963dced",
      "syslanguage" : [ "English" ],
      "transactionid" : 149713,
      "title" : "401 - You must provide credentials to perform this operation - NoAuthenticationException (Coveo for Salesforce)",
      "date" : 1513887516000,
      "objecttype" : "Developers Topic",
      "audience" : [ "Developer" ],
      "sysconnectortype" : "ConfluenceCrawler",
      "cfspacename" : "Coveo Support Knowledge Base",
      "rowid" : 4755000,
      "size" : 155511,
      "clickableuri" : "https://developers.coveo.com/pages/viewpage.action?pageId=36644285",
      "syssource" : "developers",
      "orderingid" : 212380408708762555,
      "syssize" : 155511,
      "sysdate" : 1513887516000,
      "sysparents" : "<parents><parent name=\"Coveo Support Knowledge Base\" uri=\"https://developers.coveo.com/display/SupportKB\" /><parent name=\"Coveo Support KB\" uri=\"https://developers.coveo.com/display/SupportKB/Coveo+Support+KB\" /><parent name=\"Coveo for Salesforce - Support KB\" uri=\"https://developers.coveo.com/display/SupportKB/Coveo+for+Salesforce+-+Support+KB\" /></parents>",
      "syscfspacename" : "Coveo Support Knowledge Base",
      "author" : "Alexandre Moreau",
      "source" : "developers",
      "cfspacetype" : "401 - You must provide credentials to perform this operation - NoAuthenticationException (Coveo for Salesforce)",
      "collection" : "default",
      "indexeddate" : 1513890271000,
      "connectortype" : "ConfluenceCrawler",
      "filetype" : "CFPage",
      "sysclickableuri" : "https://developers.coveo.com/pages/viewpage.action?pageId=36644285",
      "sysfiletype" : "CFPage",
      "language" : [ "English" ],
      "sitename" : "Developers",
      "sysrowid" : 4755000,
      "uri" : "https://developers.coveo.com/display/SupportKB/Page/3080921/24641753/36644285",
      "syscollection" : "default",
      "sitelanguage" : [ "English" ]
    },
    "Title" : "401 - You must provide credentials to perform this operation - NoAuthenticationException (Coveo for Salesforce)",
    "Uri" : "https://developers.coveo.com/display/SupportKB/Page/3080921/24641753/36644285",
    "PrintableUri" : "https://developers.coveo.com/display/SupportKB/Page/3080921/24641753/36644285",
    "ClickUri" : "https://developers.coveo.com/pages/viewpage.action?pageId=36644285",
    "UniqueId" : "42.58196$https://developers.coveo.com/display/SupportKB/Page/3080921/24641753/36644285",
    "Excerpt" : "This is the simplest cause. ... We've seen occurrences where the link between the Coveo for Salesforce package on the customer Salesforce instance, and the Coveo org, have correctly been created by...",
    "FirstSentences" : null
  }